cosmos/interchain-security

Makefile
go.sum
third_party/proto/confio/proofs.proto
third_party/proto/cosmos/base/query/v1beta1/pagination.proto
third_party/proto/cosmos/staking/v1beta1/staking.proto
third_party/proto/cosmos/upgrade/v1beta1/upgrade.proto
third_party/proto/cosmos_proto/cosmos.proto
x/ccv/provider/types/query.pb.gw.go

Fix `make proto-gen`:
- get `staking.proto` from cosmos/cosmos-sdk/interchain-security-rebase 
- get `cosmos.proto` needed by `staking.proto`
- update confio version
- remove `gogo.proto` from `make proto-update-deps`

Fix proto-gen

---

x/ccv/provider/keeper/keeper.go
x/ccv/provider/unbonding_hook_test.go

Unbonding ops are put on hold even w/o consumer chains

---

testutil/simapp/simapp.go

remove unused code
closes #112

chore: remove unused code

---

app/consumer/app.go

Pass consumer keeper to ante handler options in consumer app.go

Make pass the tests after #113

---

x/ccv/consumer/module.go

Fixes
- https://github.com/cosmos/interchain-security/issues/106

Ensure VSCMature packets are sent even if no ValidatorUpdates are received

---

app/consumer/app.go
app/consumer/export.go
app/provider/app.go
go.mod
go.sum
x/ccv/consumer/keeper/keeper_test.go
x/ccv/consumer/keeper/validators.go
x/ccv/consumer/module_test.go
x/ccv/consumer/types/keys.go
x/ccv/provider/keeper/keeper_test.go
x/ccv/provider/provider_test.go
x/ccv/provider/unbonding_hook_test.go

Disable the staking module from the consumer chain.
* Close #139 
* Built upon #152 & #150
The following changes are required due to ibc-go testing limitations:
-  The consumer `UnbondingTime` value is set to match the ibc-go testing [default client config](https://github.com/cosmos/ibc-go/blob/a71fc1029ad1fc6d377d642781d02ad3cbfa0910/testing/endpoint.go#L48-L53) (see #153).
-  The `GetSakingKeeper` function signature in `app.go`s returns an [ibcclienttypes.StakingKeeper](https://github.com/cosmos/ibc-go/blob/a71fc1029ad1fc6d377d642781d02ad3cbfa0910/modules/core/02-client/types/expected_keepers.go#L12) interface rather than a concrete [StakingKeeper type](https://github.com/cosmos/cosmos-sdk/blob/748b9f08bc77e36047175a14313c4d593846ce4f/x/staking/keeper/keeper.go#L24).

MVCC part B

---

app/consumer/ante_handler.go
app/consumer/app.go
app/provider/ante_handler.go
app/provider/app.go
go.mod
go.sum
x/ccv/consumer/module.go
x/ccv/consumer/module_test.go
x/ccv/provider/module.go

Together with 
- https://github.com/informalsystems/ibc-go/pull/4
tackles
- https://github.com/cosmos/interchain-security/issues/107
Long story short, the v3.0.0 that cosmwasm uses changes the signature of `OnChanOpenAck` so this had to be changed on interchain-sec side. On ibc-go side I rebased onto v3.0.0. 
Note that
- https://github.com/informalsystems/ibc-go/pull/4
should be merged first as I'll have to change the version in go.mod here.

Upgrade to ibc go v3.0.0

---

go.mod
integration-tests/actions.go
integration-tests/main.go
integration-tests/testnet-scripts/start-chain.sh

This PR fixes the driver. The driver is now able to drive actions. This PR does not fix the actual test contents, which can be found in [steps.go](https://github.com/cosmos/interchain-security/blob/main/integration-tests/steps.go), [steps.json](https://github.com/cosmos/interchain-security/blob/main/integration-tests/steps.json). This PR also does not fix the SUT. Therefore, the integration tests are _still failing_, although this PR does make the driver correct.
Closes 
- https://github.com/cosmos/interchain-security/issues/167
Does _not_ close
- https://github.com/cosmos/interchain-security/issues/168
Credit to @sainoe for the actual logical fixes.

Fix integration test driver #167

---

x/ccv/provider/keeper/keeper_test.go
x/ccv/provider/provider_test.go

These calls were a hack that was needed when we only had one app.go. So now they should be removed.

Removes DisableConsumerDistribution calls

---

Makefile
app/consumer-democracy/ante/msg_filter_ante.go
app/consumer-democracy/ante/msg_filter_ante_test.go
app/consumer-democracy/ante_handler.go
app/consumer-democracy/app.go
app/consumer-democracy/export.go
app/consumer-democracy/genesis.go
cmd/interchain-security-cdd/main.go
x/ccv/distribution/module.go

closes #https://github.com/cosmos/interchain-security/issues/141

create consumer-democracy application

---

app/provider/app.go

Closes https://github.com/cosmos/interchain-security/issues/51

Order of EndBlock

---

app/provider/export.go
integration-tests/actions.go
integration-tests/main.go
integration-tests/state.go
x/ccv/consumer/keeper/keeper.go
x/ccv/consumer/keeper/relay.go
x/ccv/consumer/module.go
x/ccv/provider/client/proposal_handler.go
x/ccv/provider/keeper/keeper.go
x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/relay.go
x/ccv/provider/module.go
x/ccv/types/ccv_test.go

Closes #223 and #228
Comments: 
- SonarCloud analysis is still failing due to repetition in new code (expected for error handling) 
- I chose to be explicit and tag each instance which should bypass gosec's warning: ```G204 (CWE-78): Subprocess launched with a potential tainted input or cmd arguments```. If the integration-tests directory is _never_ relevant to gosec, I can add a one-liner to exclude that directory from the lint altogether
- I added a call to ```filepath.Clean()``` [here](https://github.com/cosmos/interchain-security/blob/make-gosec-pass/x/ccv/provider/client/proposal_handler.go#L119), following [this suggestion](https://stackoverflow.com/questions/52320708/how-to-handle-gosec-linter-warning-potential-file-inclusion-via-variable/52321435). From my understanding of the …

Make gosec pass

---

x/ccv/consumer/keeper/relay.go
x/ccv/consumer/module.go

Closes https://github.com/cosmos/interchain-security/issues/244
There's not much to gain from accessing the provider channel both inside and outside the UnbondMaturePackets method

Fix UnbondMaturePackets

---

x/ccv/consumer/keeper/distribution.go
x/ccv/consumer/keeper/keeper.go
x/ccv/consumer/keeper/relay.go
x/ccv/consumer/keeper/validators.go
x/ccv/consumer/types/keys.go
x/ccv/consumer/types/keys_test.go
x/ccv/provider/keeper/genesis.go
x/ccv/provider/keeper/keeper.go
x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/proposal_test.go
x/ccv/provider/module.go
x/ccv/provider/types/keys.go
x/ccv/provider/types/keys_test.go
x/ccv/types/keys.go

Closes https://github.com/cosmos/interchain-security/issues/18
Prefixes and singular keys are now defined as byte constants, assigned with iota. Corresponding helpers returning ```[]byte``` are defined in the same file as the byte constants. 
Comments: 
1. This PR enforces the semantics of a "key"/"singular key" and a "key prefix" in some places. The former being a key associated to a single value (or a single sequence of values marshaled/unmarshaled together), while the latter is a prefix where further bytes are appended to the key to retrieve values.
2. It may be worth standardizing on where/if we use separators at all. **Update after discussions** - Separators (```"/"```) were removed wherever possible from existing key functions.

Constant Length Key Prefixes

---

integration-tests/actions.go
integration-tests/steps.go

Closes https://github.com/cosmos/interchain-security/issues/168
Removes a couple auxiliary smoke tests to allow integration tests to pass ASAP. Also corrects an outdated cli command for hermes. Future work will check that no tokens can be sent on the consumer chain before the ICS channel is setup, but can be sent after the channel is setup (need to confirm this is the expected behavior)
Green check woo! Cred to Jehan

Fix integration tests

---

Dockerfile

Avoids future issues similar to what was solved in #248, where the newest version of hermes introduced breaking changes to integration test setup. This change specifies that the integration test docker container will always use [v0.15.0 (latest)](https://github.com/informalsystems/ibc-rs/releases/tag/v0.15.0)

Specify hermes version for integration tests

---

integration-tests/steps.go

Adds back the check that was removed in https://github.com/cosmos/interchain-security/pull/248, which confirms that a "send tokens" action _will not_ execute on a consumer chain (ie. the tx is filtered out by ante handler) before the ICS channel is fully initialized, and that the "send tokens" action _will_ execute properly on a consumer chain after the ICS channel is fully initialized.

Add additional transaction checks to integration tests

---

x/ccv/provider/keeper/proposal_test.go

@mpoke something like this should fix your branch. The changes in #254 will throw an error if two ```createConsumerProposal```s are set for a single chain id. Alternatively, we can allow multiple proposals to be submitted for a single chain id, and ignore duplicates without throwing error. 
Related to #160, have we come to an agreement on best design patterns for this issue?

small test fix for #254

---

x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/proposal_test.go
x/ccv/provider/proposal_handler_test.go
x/ccv/provider/types/errors.go
x/ccv/provider/types/proposal.go

Closes https://github.com/cosmos/interchain-security/issues/155

Drop duplicate spawn/stop proposals

---

Dockerfile
integration-tests/actions.go
integration-tests/main.go
integration-tests/steps.go

Closes #94, Adds relevant action and state check to test basic unbonding functionality.
While implementing this PR, the error mentioned [here](https://github.com/informalsystems/ibc-rs/issues/2536) presented itself from hermes CLI. The solution was to adjust the non-default tendermint consensus parameters used in integration tests. Before finding that solution, I did the work to migrate the integration test driver from using hermes ```v0.15.0``` to ```v1.0.0-rc.1```. These changes are included in this PR since it doesn't hurt to use a newer version of hermes. More detail on the differences [here](https://github.com/informalsystems/ibc-rs/blob/v1.0.0-rc.1/UPGRADING.md).

Integration Test Addition - Unbonding

---

.github/CODEOWNERS
x/ccv/consumer/keeper/genesis.go
x/ccv/consumer/keeper/genesis_test.go
x/ccv/consumer/keeper/keeper.go
x/ccv/consumer/keeper/keeper_test.go
x/ccv/consumer/module_test.go
x/ccv/consumer/types/keys.go
x/ccv/consumer/types/keys_test.go
x/ccv/provider/keeper/keeper_test.go
x/ccv/provider/provider_test.go

Addressing https://github.com/cosmos/interchain-security/pull/274#discussion_r951393772 in it's own PR.
Also changes setter

GetProviderClient -> GetProviderClientID

---

app/consumer/ante/disabled_modules_ante.go
app/consumer/ante/disabled_modules_ante_test.go
app/consumer/ante_handler.go

This pull request fixes issue #115 by adding new ante decorator that disables messages from evidence and slashing modules.
Messages from staking, governance and distribution modules don't need to be filtered since those modules don't exist in minimal consumer chain. If someone sends any of those messages, the CheckTx() will fail because messages from this modules can not be deserialized from bytes to Go structs.
The fix addresses only minimal viable consumer chain. Enabling/disabling of governance, staking and distribution messages for consumer chains with the "democracy package" will be implemented through issue #141.

Disable messages on consumer chain

---

e2e-tests/valset_update_test.go
x/ccv/consumer/keeper/relay.go
x/ccv/consumer/module.go

The naming of ```UnbondMaturePackets``` did not make sense to me. This PR changes the name to help quick readers

(small change): Naming of UnbondMaturePackets

---

x/ccv/consumer/types/params.go
x/ccv/provider/types/keys.go
x/ccv/provider/types/params.go

This PR addresses isue #280.
Usage of magic numbers is reduced and replaced with defined constants.
Magic numbers remain in tests and testutils.
`golangci-lint` was used to discover the magic numbers.
Linter configuration can be found [here](https://gist.github.com/MSalopek/191fc6e493286aab33448506d2fecebe).
Comprehensive configuration options can be found [here](https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml)
It might be beneficial to setup `golangci-lint` to run as precommit hook in the future.

reduce usage of magic numbers and replace with constants

---

tests/e2e/channel_init_test.go
x/ccv/provider/client/proposal_handler.go
x/ccv/provider/types/proposal.go
x/ccv/provider/types/proposal_test.go

The ```NewCreateConsumerChainProposal``` function previously returned a useless error that would always be nil. The function only constructs an in-mem type without any marshaling, so it's safe to remove the returned error.
This PR makes existing and incoming unit tests simpler

Bugfix and refactor NewCreateConsumerChainProposal

---

tests/e2e/distribution_test.go
x/ccv/consumer/keeper/distribution.go

Added e2e test for distributing rewards from minimal viable consumer chain to the corresponding consumer account and provider chain.
Also, this includes a change in consumer's distribution logic that will transfer the rewards to the consumer and provider redistribute addresses in each block. This change is first introduced [here](https://github.com/cosmos/interchain-security/blob/4915a0a9c7150e1dc8516950dd52930785e427b5/x/ccv/consumer/keeper/distribution.go#L66) , but it is implemented here as well so that once the original [PR](https://github.com/cosmos/interchain-security/pull/130) is pushed, the test stays valid.

Test for the reward distribution

---

Makefile
README.md

Adds new commands to makefile:
* make test-short (unit, e2e)
* make test-diff (difference tests only)
* make test-integration (integration tests only)
* make test-no-cache (equivalent to make test with caching disabled)
Closes: #345

allow selecting test granularity using make

---

Makefile
README.md

Reading through https://github.com/cosmos/interchain-security/issues/345 it seems there was agreement on implementing
```bash
make test-fast
make test
```
Where make test would run all four of unit, e2e, diff, and integration tests. 
This PR slightly modifies #350 to make sure the make file aligns with the readme, and that all tests are included in ```make test```

Extend #350

---

Makefile
go.sum
proto/buf.lock
scripts/protocgen.sh
third_party/proto/cosmos/staking/v1beta1/staking.proto

An issue manifested because buf dependencies were out of date.
Running `make proto-gen` would fail with err citing that googleapis depedency cannot be found.
Updated buf dependencies using
buf mod update --only buf.build/googleapis/googleapis
Changed tidy to be compatible to 1.18 only
Closes: #347

update buf googleapis dependency

---

docs/interchain-security/proto-docs.md
docs/quality_assurance.md
proto/interchain_security/ccv/provider/v1/provider.proto
tests/e2e/channel_init_test.go
tests/e2e/stop_consumer_test.go
tests/integration/actions.go
tests/integration/main.go
tests/integration/state.go
tests/integration/steps.go
x/ccv/provider/client/proposal_handler.go
x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/proposal_test.go
x/ccv/provider/module.go
x/ccv/provider/proposal_handler.go
x/ccv/provider/types/codec.go
x/ccv/provider/types/errors.go
x/ccv/provider/types/keys.go
x/ccv/provider/types/keys_test.go
x/ccv/provider/types/proposal.go
x/ccv/provider/types/proposal_test.go
x/ccv/provider/types/provider.pb.go
x/ccv/types/errors.go

Changes all instances, comments, methods, etc. such that:
- ```CreateConsumerChainProposal``` (the abstract type) is now ```ConsumerAdditionProposal```
- ```StopConsumerChainProposal``` (the abstract type) is now ```ConsumerRemovalProposal```
- ```StopConsumerChainProposal()``` (the method) is now ```HandleConsumerRemovalProposal()```
- ```CreateConsumerChainProposal()``` (the method) is now ```HandleConsumerAdditionProposal()```
Related to #331

Proposal naming refactors

---

x/ccv/provider/keeper/keeper.go
x/ccv/provider/keeper/keeper_test.go
x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/relay.go

Partially addresses
- https://github.com/cosmos/interchain-security/issues/331
We had some methods prefixed with `Empty` which I found confusing.

Rename Empty prefix to Consume

---

x/ccv/consumer/keeper/params_test.go
x/ccv/consumer/keeper/relay.go
x/ccv/consumer/types/genesis.go
x/ccv/consumer/types/genesis_test.go
x/ccv/consumer/types/params.go
x/ccv/consumer/types/params_test.go
x/ccv/provider/types/params.go
x/ccv/types/shared_params.go

Consumer genesis params were previously not validated on `ValidateGenesis`, now they are. This is consistent with how validation is done for provider genesis. These changes are needed for #393 
Note genesis param validation may be redundant with the checks that happen internally for `SetParams` in `InitGenesis`. An alternative to the current changes in this PR is removing genesis param validation altogether from consumer and provider. No matter what, we should be consistent between consumer and provider

Consistent params validation

---

tests/difference/core/driver/setup.go

@smarshall-spitzbart this should address the issue

diff test patch

---

tests/e2e/channel_init.go
tests/e2e/common.go
tests/e2e/setup.go
x/ccv/provider/keeper/proposal.go

Closes https://github.com/cosmos/interchain-security/issues/436.
This PR removes the code that is confusing and effectively dead. IBC client states are actually setup [here](https://github.com/cosmos/interchain-security/blob/e2e-setup-cleanup/x/ccv/provider/keeper/proposal.go#L61) and [here](https://github.com/cosmos/interchain-security/blob/e2e-setup-cleanup/x/ccv/provider/keeper/proposal.go#L212), using correct convention of the client state's unbonding period being for the counterparty chain.
Aside: The nomenclature of how "providerClientState", "consumerClientState", etc. are used in this repo is pretty inconsistent. "consumerEndpointClientState", etc. is easier for me to understand as the client state used on the consumer's IBC endpoint

E2e setup cleanup

---

tests/e2e/slashing.go
x/ccv/provider/keeper/keeper.go

Improves a couple slashing related e2e tests by:
1. Removing duplicate test/setup code in favor of test cases and if-statements (TestSendSlashPacketDowntime and TestSendSlashPacketDoubleSign were 90% the same, now they are one test method)
2. Removing a hack which previously reconstructed a VSC packet from local variables, and manually sent/received that packet using IBC testing functions
3. Using `providerSlashingKeeper.SlashFractionDowntime` instead of hardcoding an expected slash fraction
The second point here is needed to properly tie https://github.com/cosmos/interchain-security/pull/462 into existing e2e tests, the hack was faultily making e2e tests fail.

Slashing related e2e test improvements

---

x/ccv/provider/module.go

Closes https://github.com/cosmos/interchain-security/issues/428
Note that the vscID is already initialized from genesis in InitGenesis, see https://github.com/cosmos/interchain-security/blob/e0cbf9a8f17cb03d03604954ef8685d82d518ea5/x/ccv/provider/keeper/genesis.go#L27

Remove false vscID initialization 

---

go.mod
go.sum
tests/e2e/common.go

Closes #493 by referencing a new head of our [IBC fork](https://github.com/informalsystems/ibc-go/commits/interchain-security-2). See relevant IBC repo changes in https://github.com/informalsystems/ibc-go/pull/10

Improve how sent packets are stored in e2e tests 

---

app/consumer-democracy/app.go
app/consumer/app.go
testutil/e2e/interfaces.go
x/ccv/consumer/keeper/keeper.go
x/ccv/consumer/keeper/keeper_test.go
x/ccv/consumer/keeper/relay.go
x/ccv/provider/keeper/relay.go
x/ccv/types/events.go

Closes: #435 
This is a follow-up to PR #448 
Removed events were reintroduced.
Comment strings were updated. Deleting maturity time during iteration was refactored.

refactor changes in expired consumer handling

---

tests/e2e/slashing.go
tests/integration/main.go
tests/integration/steps.go

Turn off multi-consumer integration tests to prevent them from timing out when run in CI.

deactivate multi-consumer tests for goc-december

---

x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/proposal_test.go

Update tags to keep consistent with the spec. 
Closes: https://github.com/cosmos/interchain-security/issues/390

Update tags for HandleConsumerAdditionProposal and HandleConsumerRemovalProposal

---

x/ccv/provider/handler_test.go
x/ccv/provider/keeper/hooks.go
x/ccv/provider/keeper/hooks_test.go
x/ccv/provider/keeper/key_assignment.go
x/ccv/provider/keeper/key_assignment_test.go
x/ccv/provider/types/errors.go
x/ccv/types/expected_keepers.go

Fixes
- https://github.com/cosmos/interchain-security/issues/503

Fixes #503 prevents two key assignment key overlap security issues

---

x/ccv/provider/keeper/keeper.go
x/ccv/provider/keeper/keeper_test.go
x/ccv/provider/keeper/relay.go

`provider.EndBlockCCR` removes chains which timed out. However, when iterating through all chains, it stops as soon as it finds one chain that did not time out, falsely assuming that the chains are ordered by their time of arrival <=> expiration time.
Closes: #513 
This bug was found during code audit.

fix IterateInitTimeoutTimestamp

---

tests/e2e/throttle.go
tests/integration/config.go
tests/integration/steps_double_sign.go
testutil/e2e/debug_test.go
x/ccv/provider/keeper/relay.go
x/ccv/provider/keeper/throttle.go
x/ccv/provider/keeper/throttle_test.go
x/ccv/provider/types/keys_test.go
x/ccv/provider/types/throttle.go
x/ccv/types/ccv.go

This PR solves two bugs found from diff tests on #462, thank you for finding these @danwt! It also closes an issue raised about the integration of key assignment and throttling.
Bug 1: https://github.com/cosmos/interchain-security/pull/462#discussion_r1041337359
Bug 2: https://github.com/cosmos/interchain-security/pull/462#issuecomment-1339845142
Issue fixed: #538 
Closes #538 
- E2E tests
- Integration
This will need to be cherry-picked into `goc-december` and `circuit-breaker`

Throttle bug fixes + req refactors

---

tests/difference/core/driver/core_test.go
tests/difference/core/driver/setup.go
tests/difference/core/model/src/common.ts
tests/difference/core/model/src/constants.ts
tests/difference/core/model/src/model.ts

Adjusts the diff tests core model to tests scenarios where the throttle `fraction=1.0` and the throttle is replenished every block.
```
prams.SlashMeterReplenishFraction = "1.0"
prams.SlashMeterReplenishPeriod = time.Second * 1
```
This should allow all slashes to occur as per the spec as if the throttle didn't exist. This is a good baseline to get into the testnet and main until the full spec can be flesh out and more throttle scenarios can be tested (#534)
Issue
- https://github.com/cosmos/interchain-security/issues/533

#533 throttle normal operation diff testing PR rebase 2

---

tests/e2e/expired_client.go
tests/e2e/key_assignment.go
tests/e2e/stop_consumer.go
tests/e2e/unbonding.go
x/ccv/provider/keeper/genesis.go
x/ccv/provider/keeper/genesis_test.go
x/ccv/provider/keeper/keeper.go
x/ccv/provider/keeper/keeper_test.go
x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/relay.go
x/ccv/provider/keeper/relay_test.go

Changes instances where "packets" is used on the provider to refer to VSC packets. 
#462 will queue VSC Matured packets and Slash packets on the provider. So we now need to be more granular when using the term "packets". There are also places where e2e or diff tests refer to "packets" when talking about any type of IBC packet.
Entirely refactor

Refactor: `Packets` -> `VSCPackets`

---

go.mod
go.sum

Updates Gaia dependency to most up to date version of [gaia with ICS integration](https://github.com/cosmos/gaia/commit/f73f97517b5beeb60aa6a639f2dc55448f86bd69)
https://github.com/cosmos/gaia/pull/1938

chore: Update gaia dependency for e2e provider test

---

x/ccv/utils/utils.go
x/ccv/utils/utils_test.go

This adds sorting to the AccumulateChanges function to stop relying on Go map iteration order.
Closes: #505
Is not tested under actual map iteration nondeterminism because this is hard to trigger intentionally. Still, the code is simple enough that this probably is ok.

add sorting into AccumulateChanges and add a unit test for it

---

tests/e2e/stop_consumer.go
tests/e2e/throttle.go
x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/proposal_test.go
x/ccv/provider/keeper/throttle.go
x/ccv/provider/keeper/throttle_test.go
x/ccv/provider/types/keys.go
x/ccv/provider/types/keys_test.go

Refactor to abide by iterator best practices, should not change any underlying behavior of throttling.
All tests in `throttle_test.go`, particularly `getAllThrottledPacketDataInstances`

Circuit breaker refactor

---

tests/e2e/unbonding.go
tests/integration/actions.go
testutil/keeper/expectations.go
x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/proposal_test.go
x/ccv/types/errors.go

This PR prevents consumer proposal executions to halt the provider in `BeginBlock`. 
Proposals  are now always executed in a cached context in order to either write or rollback the states, depending on the returned errors and the calling methods.
Therefore, the provider's `BeginBlocker` logic either writes or discards the proposals resulting states preventing the chain to halt due to invalid proposals.
The behavior of the proposal handlers has been changed in two ways: first, proposal execution is always verified, and second, successfully checked proposals are added to the pending proposals store regardless of their `spawn/stop` time.
Closes: #463, #458 …

fix: verify consumer proposals execution to prevent provider halts

---

x/ccv/consumer/keeper/keeper.go
x/ccv/consumer/keeper/relay.go
x/ccv/consumer/types/keys.go
x/ccv/provider/keeper/keeper.go
x/ccv/provider/types/keys.go

Replaces 
- `binary.BigEndian.Uint64` with `sdk.BigEndianToUint64`
- `binary.BigEndian.PutUint64` with `sdk.Uint64ToBigEndian`
NA

Use SDK utility function instead of encoding/binary

---

proto/interchain_security/ccv/provider/v1/query.proto
tests/integration/state.go
x/ccv/provider/client/cli/query.go
x/ccv/provider/keeper/grpc_query.go
x/ccv/provider/types/query.pb.go
x/ccv/provider/types/query.pb.gw.go

Refactors for #600 considering updated terminology. TLDR is that the latest revision of throttling is pretty careful about what types it's referencing. "packet" could mean a lot of things, so we reserve that for the IBC packet type, where our types are "slash packet data" ,"global entry" etc. 
Haven't tested yet

Throttle queries refactors

---

x/ccv/provider/keeper/throttle.go
x/ccv/provider/keeper/throttle_test.go

Adds test for `GetSlashAndTrailingData`, to make sure all iteration methods from https://github.com/cosmos/interchain-security/issues/454 are tested in #596. @mpoke feel free to merge whenever

Add test for GetSlashAndTrailingData

---

x/ccv/provider/keeper/genesis.go
x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/proposal_test.go
x/ccv/provider/types/keys.go
x/ccv/provider/types/keys_test.go

Store both consumer addition proposals and consumer removal proposals under keys with the format `prefix | timestamp.UnixNano() | chainID` to enable the iteration in order of timestamps.  
Closes:  https://github.com/cosmos/interchain-security/issues/537
Updated the tests to check that the iteration is in the expected order, see `TestGetConsumerAdditionPropsToExecute`, `TestGetAllConsumerAdditionProps`, `TestGetConsumerRemovalPropsToExecute`, `TestGetAllConsumerRemovalProps`.

Fix: Change keys for storing proposals

---

tests/e2e/slashing.go

See https://github.com/cosmos/interchain-security/pull/633#discussion_r1062907598
n/a

Slash undeleg test addition

---

x/ccv/provider/types/errors.go
x/ccv/provider/types/msg.go

This is a tiny fix to make sure the AssignConsumerKey message is validated properly. The pattern is similar what they use in the staking module for the CreateValidatorMsg.
https://github.com/cosmos/cosmos-sdk/blob/main/x/staking/types/msg.go#L89
See comment
https://github.com/cosmos/interchain-security/pull/642#discussion_r1063385536

Improved assign consumer key msg validation

---

x/ccv/provider/keeper/key_assignment.go
x/ccv/provider/types/genesis.go
x/ccv/provider/types/key_assignment.go

Adds a ValidateBasic util function in /provider/types for KeyAssignment data. Uses it in ValidateGenesis. 
It's a bit verbose, but simple. Note that the vscid's are not checked! They are uints
- https://github.com/cosmos/interchain-security/issues/645

Adds ValidateBasic for key assignment related state in provider genesis

---

tests/e2e/slashing.go
x/ccv/provider/keeper/grpc_query.go
x/ccv/provider/keeper/hooks.go
x/ccv/provider/keeper/key_assignment.go
x/ccv/provider/keeper/key_assignment_test.go
x/ccv/provider/types/genesis.go
x/ccv/utils/utils.go

WIP, optionally we can audit the key related panics in `x/ccv/utils/utils.go` in this PR as well.
**_EDIT:_** 
Works toward https://github.com/cosmos/interchain-security/issues/621
If `Refactor`, describe the new or existing tests that verify no behavior was changed or added where refactors were introduced.
If `Feature` or `Fix`, describe the new or existing tests that verify the new behavior is correct and expected.

Key assignment related panic cleanup

---

tests/e2e/stop_consumer.go
x/ccv/provider/ibc_module.go
x/ccv/provider/keeper/proposal_test.go
x/ccv/provider/keeper/relay.go
x/ccv/provider/keeper/relay_test.go
x/ccv/provider/keeper/throttle.go
x/ccv/provider/keeper/throttle_test.go
x/ccv/provider/types/keys.go
x/ccv/provider/types/keys_test.go

For every panic in `throttle.go` or closely related files, this PR either: 
1. Clarifies with comments why the panic is still included
2. Removes the panic in favor of an error log to prevent undesirable binary behavior
Works toward https://github.com/cosmos/interchain-security/issues/621
n/a, fix was small and only related to queries

Throttle related panic cleanup

---

go.mod
go.sum

Small change to prevent these noisy logs from showing up every time we run tests
```
cgo-gcc-prolog:81:11: warning: 'SecKeychainCreate' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:301:10: note: 'SecKeychainCreate' has been explicitly marked deprecated here
cgo-gcc-prolog:139:11: warning: 'SecKeychainLock' is deprecated: first deprecated in macOS 12.0 - Custom keychain management is no longer supported [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecKeychain.h:357:10: note: 'SecKeychainLock' has been …
```

Removes depreciated keyring dependency 

---

tests/difference/core/driver/core_test.go
tests/difference/core/model/src/model.ts

Removes some TODOs, clarifies one
Refactor

Difftest core: small PR removes some todos

---

.github/workflows/manual-integration.yml
.github/workflows/nightly-integration.yml

Add `nightly` test run which includes all integration tests and executes them using a cronjob. The test will be performed every night at 03:00 (AM).
The `nightly` test run will notify a selected slack channel via a webhook configured for this repo.
Add manual trigger for integration tests running on `main` branch.
Closes: #514 #631 
Depends on: #659 

add manual integration tests GH workflow

---

tests/integration/actions.go
tests/integration/steps_downtime.go

The diffs in #687 caused integration tests to fail, which is actually good and proves that the patch changed behavior. This PR fixes integration tests to be a bit more granular with the throttle behavior that's expected.
Full integration tests pass locally for me, `make test-integration`

Throttle integration test fixes

---

tests/integration/actions.go
tests/integration/steps_democracy.go
tests/integration/steps_double_sign.go
tests/integration/steps_downtime.go
tests/integration/steps_multi_consumer_downtime.go

Updates integration tests to reflect consumer initiated slashing changes.
Related to: #689 

update integration tests with new consumer initiated slash behaviour

---

tests/integration/actions.go

Adding a wait time after sending an unjail tx so it has a chance to be included in a block and the required packets to be commited.
Previously, when making state assertions after unjailing the validator's jailed state sould not change and their power would not be refreshed. 
Closes: #631 

wait after sending unjail tx in integration tests

---

tests/e2e/slashing.go
testutil/keeper/expectations.go
x/ccv/provider/keeper/relay.go
x/ccv/provider/keeper/relay_test.go

Supersedes https://github.com/cosmos/interchain-security/pull/694. Please do not merge until #692 is merged!
Closes: #693 
`TestRelayAndApplyDowntimePacket` was refactored to make sure that the consumer's outstanding downtime flag is properly deleted
`TestHandleSlashPacket` now has functionality for checking slash acks

Fix slash acks bug

---

docs/architecture/adr-002-throttle.md

In this commit I tried to make some notions more precise, correct some typos, and add extra explanations where I thought they were necessary.
In particular, I replaced the assumption of the "final jailed provider smaller than F" with the assumption of "every provider smaller than F". The reason is that it is up to adversary to choose the last slashed provider and thus we need to have this stronger assumption.
Other changes are mostly about formatting and adding gluing explanations.

invariant explanation made more precise; some extra clarifications

---

tests/e2e/throttle.go
tests/integration/steps.go
tests/integration/steps_double_sign.go
tests/integration/steps_multi_consumer_double_sign.go
tests/integration/steps_submit_equivocation_proposal.go
x/ccv/provider/keeper/keeper.go
x/ccv/provider/keeper/keeper_test.go
x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/proposal_test.go
x/ccv/provider/keeper/relay.go
x/ccv/provider/keeper/relay_test.go
x/ccv/provider/proposal_handler_test.go
x/ccv/provider/types/keys.go

This PR adds additional checks regarding Equivocation governance proposals.
Any time a validator double signs on any of the consumer chains, the provider will keep a record that signifies that an equivocation slash packet was received from a consumer chain.
Any proposals made to slash validators for which the provider does not have a double signing record will be rejected.
Closes: #729 
Throttling e2e tests, unittests and integration tests were written to accomodate these changes.

add additional checks for equivocation governance proposals

---

x/ccv/provider/keeper/proposal_test.go

`TestHandleEquivocationProposal` was recently added, the test involved calling `GetConsensusAddress` for two different addresses in `HandleEquivocationProposal`, both which would return `nil`.
This PR fixes the test to use valid cons addresses, unblocking #707 
n/a
n/a

Fix TestHandleEquivocationProposal

---

.github/workflows/build.yml

Environment variable was removed from `build.yml` resulting in all SonarCloud workflows failing.
Dependabot still cannot push results to SonarCloud - we may need to prevent the SonarCloud runs on dependabot's PRs since it seems tha dependabot cannot access any of the env variables.
Change is not code related.
Change is not code related.
Change is not code related.

chore: revert build.yml changes

---

x/ccv/provider/types/keys.go
x/ccv/provider/types/keys_test.go

Replace `SlashAcksBytePrefix` with `SlashLogBytePrefix`
Closes: https://github.com/cosmos/interchain-security/issues/785
If `Feature` or `Fix`, describe the new or existing tests that verify the new behavior is correct and expected.

Ser correct byte prefix for SlashLogKey 

---

tests/integration/actions.go
tests/integration/main.go
tests/integration/steps.go
tests/integration/steps_stop_chain.go
x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/proposal_test.go

This PR resolves a bug in `StopConsumerChain`.
A bug was identified in ICS provider code where the StopConsumerChain is not actually called in a cachedContext. Instead, it is run in the global app context.
This meant that the consumer chain can get removed unexpectedly and its CCV chanel was closed as soon as the proposal tx gets handled.
This bug is resolved i
Closes: #799 
Expanded existing tests to confirm that the consumer is not removed prematurely and also that it is cleanly removed when a proposal passes.

fix StopConsumerChain not running in cachedContext

---

docs/docs/consumer-development/app-integration.md
docs/docs/consumer-development/onboarding.md
docs/docs/features/proposals.md
docs/docs/features/reward-distribution.md
docs/docs/features/slashing.md
docs/docs/frequently-asked-questions.md
docs/docs/validators/joining-testnet.md
docs/docs/validators/overview.md

This PR simply fixes some typos and broken links in all documents of the `docs` directory. 

fix: fix typos and broken links

---

testutil/keeper/unit_test_helpers.go
x/ccv/consumer/keeper/changeover_test.go
x/ccv/consumer/keeper/genesis_test.go
x/ccv/consumer/keeper/keeper_test.go
x/ccv/consumer/keeper/validators_test.go

Removes `RegisterSdkCryptoCodecInterfaces` from the unit testing helpers file, and associated TODO comment. To replace this functionality `cryptocodec.RegisterInterfaces(ir)` is called for every unit test. 
A previous issue https://github.com/cosmos/interchain-security/issues/273 made it seem like we had to do these calls explicitly, but that's not the case.  
n/a
n/a
n/a

Remove RegisterSdkCryptoCodecInterfaces

---

x/ccv/consumer/keeper/keeper.go
x/ccv/consumer/keeper/relay.go
x/ccv/consumer/types/keys.go
x/ccv/provider/keeper/grpc_query.go
x/ccv/provider/keeper/hooks.go
x/ccv/provider/keeper/keeper.go
x/ccv/provider/keeper/key_assignment.go
x/ccv/provider/keeper/key_assignment_test.go
x/ccv/provider/keeper/relay.go
x/ccv/provider/types/keys.go
x/ccv/types/utils.go
x/ccv/types/utils_test.go

Moves the contents of `x/ccv/utils/` to `x/ccv/types`, which is a different golang package. Existing code now references the ccvtypes package. 
This is step 1 to complete #801  
#801
Existing UTs
n/a

refactor: move utils to /types

---

tests/e2e/actions.go
tests/e2e/step_delegation.go
tests/e2e/steps.go
tests/e2e/steps_downtime.go
tests/e2e/steps_start_chains.go

Adds e2e tests validating #765 
Closes https://github.com/cosmos/interchain-security/issues/849
Existing happy path steps are still there
Two new steps functions were added, stepsRedelegateForOptOut and stepsDowntimeWithOptOut. 

testing: e2e tests for soft opt out 

---

go.mod
go.sum

https://github.com/cosmos/interchain-security/pull/823 upgraded us to IBC 4.3, but a final commit in https://github.com/cosmos/interchain-security/pull/805, downgraded us back to IBC 4.2. See https://github.com/cosmos/interchain-security/commit/31481fa7ed5f24a1b54decc3549916396c740c8f. 
@mpoke has added an additional repo restriction that we need an approver of the most recently pushed commit for any PR. Hopefully this new rule will prevent regressions like this.
Closes: `#<issue>`
Existing tests
No new app behavior from our repo

bump: ibc 4.3

---

.github/workflows/automated-tests.yml
.github/workflows/build.yml
.github/workflows/golangci-lint.yml
.github/workflows/manual-e2e.yml
.github/workflows/nightly-e2e.yml
Dockerfile
Dockerfile.gaia
README.md
go.mod
scripts/protocgen.sh
x/ccv/provider/keeper/key_assignment_test.go
x/ccv/provider/keeper/throttle_test.go

At present we need `go1.19` for our proto files to build correctly.
Using `go 1.20` produces problems during the proto build.
```
make proto-gen
Generating Protobuf files
Generating gogo proto code
invalid value "1.20" for flag -compat: maximum supported Go version is 1.19
usage: go mod tidy [-e] [-v] [-go=version] [-compat=version]
Run 'go help mod tidy' for details.
make: *** [proto-gen] Error 2
```
This change will be reverted in a future step where we upgrade to `go1.20`, bump `ghcr.io/cosmos/proto-builder` to `>=0.11.5` to facilitate building using `cosmos/proto`.
---
I have...
*All items are required. Please add a note if the item is not …

chore: use go 1.19

---

.github/workflows/linkchecker.yml
README.md
docs/docs/adrs/adr-002-throttle.md
docs/docs/consumer-development/consumer-chain-governance.md
docs/docs/features/proposals.md
docs/docs/features/slashing.md
docs/docs/validators/overview.md
docs/old/protocol_audit.md
docs/old/quality_assurance.md
docs/old/testing.md
mlc_config.json

Closes: NA
Add CI check for markdown links in ./docs and fixing broken links 
---
I have...
I have...

ci: add check for markdown links

---

CHANGELOG.md

Closes: NA
---
I have...
I have...

Add v1.1.0-multiden changelog entry

---

Dockerfile
Dockerfile.gaia
docs/docs/consumer-development/onboarding.md
docs/docs/frequently-asked-questions.md

This PR bumps the version of hermes used to test ics to the latest tagged release, v1.4.1
closes: #922 
---
I have...
I have...

chore: bump hermes

---

tests/e2e/actions.go
tests/e2e/config.go
tests/e2e/testnet-scripts/cause-doublesign.sh
tests/e2e/testnet-scripts/reconfigure-node.sh

Fix non-determinism in relayPackets step in e2e by waiting for blocks after relaying and increase signed_blocks_window.
Closes: #967
---
I have...
* [] Included comments for [documenting Go code](https://blog.golang.org/godoc)
* [] Updated the relevant documentation or specification
I have...

fix: mitigate e2e tests relaying and non-determinism

---

app/consumer-democracy/ante_handler.go
app/consumer-democracy/app.go
app/consumer/ante_handler.go
app/provider/ante_handler.go
app/provider/app.go
x/ccv/consumer/module.go
x/ccv/provider/module.go

At AIB we worked a little bit on the sdk47/ibc-v7 migration for this repository, but then you preferred to do it on your own. Anyway, since you just merged it #918, I took the time to compare our changes and yours and I found a small list of things that could be cleaned/improved/fixed : 
- de0fc66b77f016d387d72b355111bdbc90bae7c3 remove remaining legacy LCD/REST queriers
- c8f47139e1b864b1574dc62e0678694da4e67f1c  `simulation` migration  : `ProposalContents` can be deleted if the module has no proposal messages or proposal content to be tested by simulation.
- f4b5ebb2a8bbc67dde9338b650a0ee23b19745ad replace deprecated `govv1.ParamKeyTable()` by `gov.ProvideKeyTable()`
- befa47dcb7402a6c48a74d3130f758e23a076c48 fix duplicate record of `ante.DeductFeeDecorator`. Probably the most important …

chore: sdk47 post upgrade cleanup

---

CHANGELOG.md
x/ccv/provider/keeper/migration.go

Stays consistent with changelog patterns in gaia. For a changelog included in a release branch, only include the releases that're relevant to that release branch. The only releases relevant to `release/v2.0.x` are `v1.0.0` (the only prev release that's from the same commit lineage off main), and trivially `v2.0.0` is relevant. 
I have...
I have...

docs: cleanup changelog for v2.0.0 on release/v2.0.x

---

.github/workflows/golangci-lint.yml
Makefile
tests/e2e/actions.go
tests/e2e/main.go
tests/e2e/step_delegation.go
tests/e2e/steps.go
testutil/keeper/mocks.go
x/ccv/provider/keeper/relay.go
x/ccv/types/expected_keepers.go

Closes: https://github.com/cosmos/interchain-security/issues/948
Avoids panicking the provider when an unbonding delegation was removed through a `CancelUnbondingDelegation` message. 
---
I have...
I have...

fix!: avoid panicking on CancelUnbondingDelegation 

---

CONTRIBUTING.md

Closes: NA
Add type prefix link to CONTRIBUTING.md
---
I have...
I have...

docs: Add type prefix link to CONTRIBUTING.md

---

CONTRIBUTING.md

Fixes typo in contributing.md
Fixes the links to the `others` PR template in CONTRIBUTING. 
---
I have...
I have...

docs: Fix link to template

---

Makefile

Builds on #1060 to enable the `make proto-check` test to actually work with the new way of generating protos. This approach is slightly worse, but it works and it's not worth spending anymore time on fixing `make proto-check`
---
I have...
I have...

chore: proto check that works

---

.github/workflows/automated-tests.yml
.github/workflows/build.yml
.github/workflows/golangci-lint.yml
.github/workflows/manual-e2e.yml
.github/workflows/nightly-e2e.yml
README.md
x/ccv/provider/keeper/key_assignment_test.go
x/ccv/provider/keeper/throttle_test.go

Fully closes: https://github.com/cosmos/interchain-security/issues/966
There were some spots that were missed regarding go1.19 -> go1.20
I have...
I have...

chore: finish go1.20 bump

---

tests/integration/slashing.go
x/ccv/consumer/ibc_module.go
x/ccv/consumer/keeper/relay_test.go
x/ccv/provider/ibc_module.go
x/ccv/provider/keeper/relay.go
x/ccv/types/utils.go

Note IBC core throws out error messages when constructing an error acknowledgement, see [this explanation why](https://github.com/cosmos/ibc-go/blob/6bb56d842e99cd40dbdb0e8a0066723c828a54b1/modules/core/04-channel/types/acknowledgement.go#L31). This PR introduces a new helper `NewErrorAcknowledgementWithLog` which logs the error reason when constructing an error ack. This change was needed to find a recent bug in how slash packets are marshaled to JSON.
I have...
I have...

refactor: log when constructing IBC err ack

---

tests/integration/throttle.go
x/ccv/provider/ibc_module.go
x/ccv/provider/ibc_module_test.go

Continues off #1093 
Logic shouldn't change, I just refactored out some unmarshaling code into its own func so it can be unit tested. Also the throttle integration tests use this new func instead of redefining unmarshaling logic  
I have...
I have...

refactor/test: 1093 continued

---

CHANGELOG.md
tests/integration/stop_consumer.go
testutil/integration/debug_test.go
x/ccv/consumer/module.go

Removes the panic in the consumer ccv module which would occur when the CCV channel has been closed. This will be particularly desirable for Stride where the chain could run as a POA chain if such an emergency scenario happens during or after the standalone to consumer changeover.  
This PR should not require coordinated upgrade to the best of my knowledge, in that the panic would only execute in an emergency situation for a consumer. The change should be included in the version of Stride that will be used in the upcoming changeover.  
Related to https://github.com/cosmos/interchain-security/issues/627
---
I have...
*All items are required. Please …

feat: remove consumer panic when ccv channel is closed 

---

CHANGELOG.md
tests/integration/stop_consumer.go
testutil/integration/debug_test.go
x/ccv/consumer/module.go

Backports https://github.com/cosmos/interchain-security/pull/1127 into `release/v3.1.x`

feat: remove consumer panic when ccv channel is closed  (backport #1127)

---

CHANGELOG.md

Cleans changelog for v3.1.0, this will be backported
I have...
I have...

docs: clean changelog for v3.1.0

---

docs/docs/features/proposals.md
docs/docs/validators/joining-testnet.md

Closes: NA
Appease the markdownlink linter
---
I have...
I have...

docs: update broken md links

---

.github/dependabot.yml

Closes: NA
`.dependabot.yml` is invalid and cannot be parsed after merging https://github.com/cosmos/interchain-security/pull/1140
This fixes it and makes the CI pipeline pass.
---
I have...
I have...

fix: update broken .dependabot.yml

---

tests/e2e/actions.go

Closes: #1173
* Adjust the comment to match the intended behaviour of waiting the downtime_jail_duration
* Use the WaitTime function instead of sleeping
---
I have...
I have...

test: Fix mismatching code/comment and use WaitTime instead of sleep

---

app/provider/app.go

This is work in progress. Please, do **not** review yet.
Closes: [#688](https://github.com/cosmos/interchain-security/issues/688)
Remove obsolete comment before setting the `EndBlockers` in [app.go](https://github.com/cosmos/interchain-security/blob/463ec20c87423897009bd78c2dbf96d28bd8f150/app/provider/app.go#L555-L555).
---
I have...
I have...

docs: remove an obsolete comment before setting the order of EndBlockers

---

tests/e2e/actions.go
tests/e2e/steps_start_chains.go

Closes: #1167 
This PR fixes an error in the e2e test.
When running e2e tests
- tests did not check expected error condition in assignConsumerPubKey
- transaction command to assign consensus key did not return error until '--gas auto' option was provided
---
I have...
I have...

test: Fix failing e2e test

---

Makefile
tests/e2e/actions.go
tests/e2e/main.go
tests/e2e/steps.go

Closes: #[1190](https://github.com/cosmos/interchain-security/issues/1190)
* Renames the short-happy-path to cometmock-happy-path and adds equivocation steps to it:
* It is starting to not be significantly shorter as cometmock supports more operations
* The previous name was confusing as became clear in some discussions
* Add a separate case for CometMock in equivocation
* Refactor commonly used functionality that is needed for downtime and equivocation
---
I have...
I have...

chore: Add integration for equivocation with CometMock

---

docs/docs/adrs/adr-005-cryptographic-equivocation-verification.md

Closes: #1124
---
I have...
I have...

docs: update cryptographic equivocation verification ADR

---

.github/pr_labeler.yml
.github/workflows/pr_labeler.yml

Closes: NA
---
I have...
I have...

ci: add PR labeler

---

CONTRIBUTING.md

Closes: NA
Update docs re. semantic versioning to follow ibc-go approach: https://github.com/cosmos/ibc-go/blob/main/RELEASES.md
---
I have...
I have...

docs: update semantic versioning

---

CHANGELOG.md
go.mod
go.sum

Closes: NA
Bump SDK to https://github.com/cosmos/cosmos-sdk/tree/v0.45.16-ics-lsm
---
I have...
I have...

deps: bump SDK to v0.45.16-ics-lsm

---

testutil/keeper/expectations.go
testutil/keeper/unit_test_helpers.go
x/ccv/provider/keeper/proposal_test.go
x/ccv/provider/keeper/relay_test.go
x/ccv/provider/proposal_handler_test.go

Closes: #362 
As described in this [comment](https://github.com/cosmos/interchain-security/issues/362#issuecomment-1678727931) we cannot test those methods in [ibc_module_test.go](https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/ibc_module_test.go) so we test in [relay_test.go](https://github.com/cosmos/interchain-security/blob/main/x/ccv/provider/keeper/relay_test.go) instead.
---
I have...
I have...

test: introduce tests for OnTimeoutPacket and OnAcknowledgementPacket

---

x/ccv/consumer/types/keys.go
x/ccv/types/events.go

_gosec security scanner_ started [failing](https://github.com/cosmos/interchain-security/actions/runs/5924842585/job/16063142935?pr=1169) recently with:
```
[x/ccv/types/events.go:38] - G101 (CWE-798): Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
37: 	AttributeDistributionCurrentHeight = "current_distribution_height"
> 38: 	AttributeDistributionNextHeight    = "next_distribution_height"
[x/ccv/consumer/types/keys.go:29] - G101 (CWE-798): Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
28: 	// ConsumerToSendToProviderName is a "buffer" address for outgoing fees to be transferred to the provider chain
> 29: 	ConsumerToSendToProviderName = "cons_to_send_to_provider"
```
Both are false positives because neither `next_distribution_height` or …

supress gosec false positives

---

tests/e2e/actions_consumer_misbehaviour.go
tests/e2e/main.go
tests/e2e/steps_consumer_misbehaviour.go

Closes: #1224
---
I have...
I have...

feat: improve ICS misbehaviour E2E testing coverage

---

x/ccv/provider/keeper/misbehaviour.go
x/ccv/provider/types/codec.go

Remove unnecessary code and improve doc.  See unresolved comments in #826 and #1148.
Closes: #XXXX
---
I have...
I have...

refactor: address comments of ICS Misbehaviour PRs #826 and #1148 

---

tests/e2e/actions.go

Closes: #1235 
Adds waitBlocks on both chains in relayPackets - either chain might be source or destination, and it seems inconsistent to wait only for one of the chains.
---
I have...
I have...

Add waitBlocks for *both* chains on relayPackets

---

docs/docs/adrs/adr-011-separate-releasing.md
docs/docs/adrs/adr-012-separate-releasing.md

See https://github.com/cosmos/interchain-security/issues/801 and https://github.com/cosmos/interchain-security/issues/1216. This is me documenting the info in issue comments to ADR form
I have...
I have...

docs: Create adr-012-separate-releasing.md

---

tests/integration/double_vote.go
x/ccv/provider/keeper/double_vote.go
x/ccv/provider/keeper/msg_server.go

Closes: #1261
---
I have...
I have...

fix: verify equivocation using validator pubkey in `SubmitConsumerDoubleVoting` msg

---

.github/workflows/manual-e2e.yml
.github/workflows/nightly-e2e.yml

Closes: N/A
Increases timeout from 20 to 40 minutes for `multiconsumer` nightly test run to reduce false negatives.
**Context**
After checking nightly test run failures it was determined that the test was simply killed prematurely. Additional fixes may be required if the problem persists after these changes.
---
I have...
I have...

tests: increase timeout in nightly e2e for multiconsumer

---

tests/e2e/actions.go
tests/e2e/main.go
tests/e2e/steps.go
tests/e2e/steps_light_client_attack.go

Closes: #1248 
Add three new actions that cause different types of LightClientAttackEvidence to surface on the given chain.
Also adds a new trace that makes use of this action. SInce this performs essentially exactly like double signing, I just repurpose the existing test case that works with CometMock.
When #1180 is done, it probably should add to these actions a way to do the same functionality without CometMock (see the issue for more context).
---
I have...
I have...

test: Add light client attack to e2e tests

---

docs/docs/adrs/adr-011-improving-test-confidence.md
docs/docs/adrs/adr-013-equivocation-slashing.md
docs/docs/adrs/intro.md

Closes: #1222 
Introduce an ADR that describes a first approach on slashing on the provider chain.
---
I have...
I have...

docs: introduce ADR on slashing on the provider chain

---

.gitignore
Makefile

`make build` attempted to write to the `/` root directory as
the current directory path was missing.

Fix `build` in makefile

---

tests/e2e/actions.go
x/ccv/provider/client/proposal_handler.go

Fix a typo in the e2e test of #1307 causing the `democracySteps` and `rewardDenomConsumerSteps` tests to fail.
Closes: #XXXX
---
I have...
I have...

test: fix `submitChangeRewardDenomsProposal` in e2e tests

---

CHANGELOG.md
x/ccv/consumer/keeper/migration.go
x/ccv/consumer/module.go

The consumer consensus version was not incremented in https://github.com/cosmos/interchain-security/pull/1037 when it should have been. Also `MigrateConsumerPacketData` was not registered in 1037 when it should have been. This PR fixes both issues. 
I have...
I have...

feat: increment consensus ver and register migration

---

tests/e2e/actions.go
tests/e2e/actions_sovereign_chain.go
tests/e2e/config.go
tests/e2e/main.go
tests/e2e/state.go
tests/e2e/step_delegation.go
tests/e2e/steps.go
tests/e2e/steps_democracy.go
tests/e2e/steps_double_sign.go
tests/e2e/steps_downtime.go
tests/e2e/steps_light_client_attack.go
tests/e2e/steps_multi_consumer_delegation.go
tests/e2e/steps_multi_consumer_double_sign.go
tests/e2e/steps_multi_consumer_downtime.go
tests/e2e/steps_reward_denom.go
tests/e2e/steps_sovereign_changeover.go
tests/e2e/steps_start_chains.go
tests/e2e/steps_stop_chain.go
tests/e2e/steps_submit_equivocation_proposal.go

Closes: Part of #1265 
This PR makes the fields of the relevant structs used in traces exported.
This is necessary preparation for the json format, since JSON marshal/unmarshal has problems with unexported fields, see https://stackoverflow.com/questions/11126793/json-and-dealing-with-unexported-fields.
To review this, please check that the only changes this PR makes are setting the fields of structs and types used in the e2e tests to public. In particular, the fields of all actions need to be exported.
There are also two small refactors that I have marked with comments.
---
I have...
*All items are required. Please add a note if the item is not …

tests: Export struct fields in the e2e tests

---

tests/e2e/state.go
tests/e2e/state_rapid_test.go
tests/e2e/steps_democracy.go
tests/e2e/steps_reward_denom.go
tests/e2e/tracehandler_testdata/changeover.json
tests/e2e/tracehandler_testdata/democracy.json
tests/e2e/tracehandler_testdata/democracyRewardsSteps.json
tests/e2e/tracehandler_testdata/happyPath.json
tests/e2e/tracehandler_testdata/multipleConsumers.json
tests/e2e/tracehandler_testdata/shorthappy.json
tests/e2e/tracehandler_testdata/slashThrottle.json

This is a minor-refactor PR and hence no issue is created for it.
Based on @p-offtermatt [comment](https://github.com/cosmos/interchain-security/pull/1275#discussion_r1336804594
):
> Seems ok to me. Could rename it to something like StakedTokens instead of RepresentativePowers (looking at the code, I think that's what this actually is, right?)
We rename `RepresentativePowers` to `StakedTokens`. We can see that `StakedTokens` is a better name if we look at what `getRepresentativePower` is computing, which is just the number of tokens:
```
func (tr TestConfig) getRepresentativePower(chain ChainID, validator ValidatorID) uint {
//#nosec G204 -- Bypass linter warning for spawning subprocess with cmd arguments.
bz, err := exec.Command("docker", "exec", tr.containerConfig.InstanceName, …
```

refactor: RepresentativePowers to StakedTokens

---

docs/docs/adrs/adr-005-cryptographic-equivocation-verification.md

Closes: #1266
---
I have...
I have...

doc: update ADR-005 with consumer double voting

---

tests/integration/query_providerinfo_test.go

Closes: #XXXX
Add test for this merged PR. https://github.com/cosmos/interchain-security/pull/1164
---
I have...
I have...

test: add test for queryProviderInfo

---

app/consumer-democracy/abci.go
app/consumer-democracy/ante/forbidden_proposals_ante_test.go
app/consumer-democracy/app.go
app/consumer-democracy/export.go
app/provider/app.go
cmd/interchain-security-cd/cmd/root.go
cmd/interchain-security-cdd/cmd/root.go
cmd/interchain-security-cdd/main.go
cmd/interchain-security-sd/main.go
x/ccv/democracy/governance/module.go
x/ccv/democracy/staking/module.go

democracy: update democracy consumer v50

---

docs/docs/adrs/adr-005-cryptographic-equivocation-verification.md
proto/interchain_security/ccv/provider/v1/tx.proto
x/ccv/provider/keeper/double_vote.go
x/ccv/provider/keeper/misbehaviour.go
x/ccv/provider/keeper/punish_validator.go
x/ccv/provider/types/tx.pb.go

Closes: #XXXX
---
I have...
I have...

docs: update crypto feature Godoc and ADR

---

tests/integration/misbehaviour.go
x/ccv/provider/keeper/misbehaviour.go

Closes: #1387 
---
I have...
I have...

fix: drop amnesia attacks in consumer misbehaviour handling

---

docs/docs/adrs/adr-005-cryptographic-equivocation-verification.md

Closes: #XXXX
---
I have...
I have...

doc: update cryptographic feature ADR

---

tests/integration/common.go
tests/integration/setup.go

Relates: #1349
Also remove unused func ABCIToSDKEvents.
Please go the the `Preview` tab and select the appropriate sub-template:

test: upgrade packetSniffer to latest ABCIListener API 

---

Dockerfile.gaia

Closes: N/A
Dockerfile.gaia is not pulling the latest version, contrary to what it claims in the comment.
The current line sorts by lexicographic order, i.e.
```
$ git tag
stargate-6
stargate-6-a
stargate-6-b
v0.0.0
v0.0.1-rc0
v1.0.0
v1.0.0-rc1
v1.0.0-rc2
v1.0.0-rc3
v10.0.0
v10.0.0-rc0
v10.0.1
v10.0.2
v11.0.0
v11.0.0-rc0
v12.0.0
v12.0.0-rc0
v13.0.0
v13.0.0-rc0
v13.0.1
v2.0.0
v2.0.0-rc1
v2.0.1
v2.0.10
v2.0.11
v2.0.12
v2.0.13
v2.0.14
v2.0.15
v2.0.2
v2.0.3
v2.0.4
v2.0.5
v2.0.6
v2.0.7
v2.0.8
v2.0.9
v3.0.0
v3.0.1
v4.0.0
v4.0.1
v4.0.2
v4.0.3
v4.0.4
v4.0.5
v4.0.6
v4.1.0
v4.1.1
v4.1.2
v4.2.0
v4.2.1
v5.0.0
v5.0.1
v5.0.2
v5.0.3
v5.0.4
v5.0.5
v5.0.6
v5.0.7
v5.0.8
v6.0.0
v6.0.0-rc1
v6.0.0-rc2
v6.0.0-rc3
v6.0.1
v6.0.2
v6.0.3
v6.0.4
v7.0.0
v7.0.0-rc0
v7.0.1
v7.0.2
v7.0.3
v7.1.0
v7.1.1
v8.0.0
v8.0.0-rc …
```

fix: Fix Dockerfile.gaia not pulling the latest version

---

CHANGELOG.md
tests/integration/misbehaviour.go
testutil/crypto/evidence.go
x/ccv/provider/keeper/misbehaviour.go

Closes: #1403
---
I have...
I have...

fix!: drop nil votes in misbehaviour handling

---

.github/PULL_REQUEST_TEMPLATE/production.md
CONTRIBUTING.md
RELEASE_NOTES.md
docs/docs/adrs/adr-012-separate-releasing.md

Closes: NA
Reverting the changes introduced by `ADR 012: Separate Releasing` in order to simplify the release process. The changelog will be updated in a different PR. 
---
I have...
I have...

docs: reject ADR 012

---

.github/dependabot.yml
.mergify.yml

Closes: NA
Update dependabot and mergify -- remove `-consumer` prefix from v3.2.x
---
I have...
I have...

chore: remove `-consumer` prefix from v3.2.x

---

Dockerfile
app/provider/app.go
cmd/interchain-security-pd/cmd/root.go
cmd/interchain-security-sd/cmd/root.go
tests/e2e/actions.go
tests/e2e/steps.go
tests/integration/normal_operations.go
testutil/ibc_testing/generic_setup.go
testutil/ibc_testing/specific_setup.go
x/ccv/consumer/keeper/changeover_test.go
x/ccv/consumer/keeper/keeper_test.go
x/ccv/consumer/keeper/relay_test.go
x/ccv/consumer/keeper/soft_opt_out_test.go
x/ccv/consumer/keeper/validators_test.go
x/ccv/consumer/module.go

Related: #1380 
This PR enables e2e tests.
What had to be done:
* resolve `tx slashing unjail` transaction invalid signature (use cosmos-sdk/simapp as app registration template)
* update e2e test cases to support API changes
* fix consumer module interfaces
* update consumer app tests to confirm consumer is set up correctly

tests: enable e2e tests with sdk v50, ibc-go/v8

---

.changelog/unreleased/dependencies/1373-bump-ibc.md
.changelog/unreleased/features/1336-quint-model.md
.changelog/unreleased/improvements/1324-consumer-genesis.md
.changelog/unreleased/improvements/1350-cleanup-types.md
.changelog/unreleased/state-breaking/1324-consumer-genesis.md

Closes: NA
---
I have...
I have...

docs: adding missing unreleased changes (will go in v4)

---

x/ccv/consumer/keeper/keeper.go
x/ccv/consumer/keeper/validators.go

Closes: #1427
This PR makes `GetAllValidators` method on the consumer keeper into a no-op to avoid confusion and potential errors.
The method exists to satisfy the interface expected by the slashing keeper.
---
I have...
I have...

refactor: make GetAllValidators a no-op

---

docs/docs/adrs/adr-012-separate-releasing.md

Closes: NA
---
I have...
I have...

docs: adding details of why the ADR 012 was rejected

---

.changelog/epilogue.md
CHANGELOG.md
FEATURES.md
README.md
RELEASES.md

Closes: NA
Also 
- update info on active releases
- add list of major feature per active release
---
I have...
I have...

docs: bring v2.4.0-lsm changelog section to main

---

STATE-COMPATIBILITY.md

Closes: NA
---
I have...
I have...

docs: fix SDK link

---

tests/e2e/action_rapid_test.go
tests/e2e/actions.go
tests/e2e/actions_consumer_misbehaviour.go
tests/e2e/actions_sovereign_chain.go
tests/e2e/json_utils.go
tests/e2e/main.go
tests/e2e/step_delegation.go
tests/e2e/steps_consumer_misbehaviour.go
tests/e2e/steps_democracy.go
tests/e2e/steps_double_sign.go
tests/e2e/steps_downtime.go
tests/e2e/steps_light_client_attack.go
tests/e2e/steps_multi_consumer_delegation.go
tests/e2e/steps_multi_consumer_double_sign.go
tests/e2e/steps_multi_consumer_downtime.go
tests/e2e/steps_reward_denom.go
tests/e2e/steps_sovereign_changeover.go
tests/e2e/steps_start_chains.go
tests/e2e/steps_stop_chain.go
tests/e2e/trace_handlers_test.go
tests/e2e/tracehandler_testdata/changeover.json
tests/e2e/tracehandler_testdata/consumer-double-sign.json
tests/e2e/tracehandler_testdata/consumer-misbehaviour.json
tests/e2e/tracehandler_testdata/democracy.json
tests/e2e/tracehandler_testdata/democracyRewardsSteps.json
tests/e2e/tracehandler_testdata/happyPath.json
tests/e2e/tracehandler_testdata/multipleConsumers.json
tests/e2e/tracehandler_testdata/shorthappy.json
tests/e2e/tracehandler_testdata/slashThrottle.json

Closes: #1322
---
I have...
I have...

refactor: Capitalized e2e test action name

---

docs/docs/consumer-development/changeover-procedure.md
docs/docs/consumer-development/consumer-genesis-transformation.md
docs/docs/validators/changeover-procedure.md

chore(docs/docs): typo fix

---

docs/docs/features/slashing.md

Closes: NA
---
I have...
I have...

docs: update docs on ICS slashing

---

app/consumer/genesis.go
app/consumer/genesis_test.go

Closes: #1508 
Missing transformation of ccv consumer genesis value for `new_chain` ending up in default which was preventing client creation on consumer chane. Fix for the shortcomming transforms the missing value to the exported one from provider chain. 
Fix was tested using e2e tests running consumer version v3.3.0-rc0 with provider version v2.4.0-lsm
---
I have...
I have...

fix: missing transformation for field 'new_chain' in ccv consumer genesis

---

.github/PULL_REQUEST_TEMPLATE/production.md

Closes: N/A
The PR template is inconsistently using client breaking, state breaking, library breaking.
This unifies it with the updated definitions from the RELEASE document
---
I have...
I have...

chore: Fix definition of breaking in production template

---

docs/docs/consumer-development/onboarding.md
docs/docs/features/proposals.md
docs/docs/features/reward-distribution.md
docs/docs/frequently-asked-questions.md
docs/docs/introduction/params.md
docs/docs/validators/changeover-procedure.md

Closes: #1292
Update docs on how the reward distribution works and how to whitelist reward denoms. 
---
I have...
I have...

docs: update docs for reward denom change

---

x/ccv/provider/keeper/throttle_legacy.go
x/ccv/provider/migrations/migrator.go
x/ccv/provider/migrations/v3/migration_test.go
x/ccv/provider/migrations/v3/migrations.go
x/ccv/provider/module.go

Closes: #1535 
---
I have...
I have...

chore: update migration handling for provider consensus v2->v3

---

app/consumer/genesis.go
app/consumer/genesis_test.go
docs/docs/consumer-development/consumer-genesis-transformation.md
docs/docs/validators/changeover-procedure.md

Closes: #1512
Changes will allow to transform exported consumer genesis data from version v2.x, v3.x, v4.x to a specified target version 
v2.x, v3.x, v4.x . With that newer version of provider chain exports can be transformed for older consumer chains e.g. 2.x
---
I have...
I have...

test: Add backtransform functionality to genesis transform cli

---

.github/workflows/test.yml
Dockerfile
Dockerfile.gaia

**Problem**
Trying to run the e2e tests locally would give:
```
OCI runtime exec failed: exec failed: unable to start container process: exec /usr/local/bin/hermes: no such file or directory: unknown
exit status 1
make: *** [test-e2e-short] Error 1
```
**Solution**
Fixed by adding `--platform=linux/amd64` in the relevant `FROM` statement.
Also, added the `Dockerfile` in the test GitHub actions because a change there might lead to the tests failing.
I have...
I have...

chore: fix dockerfile FROM statement

---

tests/mbt/driver/core.go
tests/mbt/driver/setup.go
tests/mbt/driver/trace_gen.go

Closes: N/A
see the errors here: https://github.com/cosmos/interchain-security/actions/runs/7479303184/job/20356165153?pr=1558
---
I have...
I have...

test: Fix gosec errors in mbt

---

Makefile

Closes: #XXXX
This PR enables showing version information for ICS test apps.
e.g.
```shell
$: interchain-security-cdd version
main-bd5b1ef2c4e3053b18083382c2dd853b0042c85e
```
---
I have...
I have...

chore: add version linker flags to make install

---

tests/e2e/actions_sovereign_chain.go

Closes: #1594 
Fix e2e tests for `chageover` feature failing on nightly tests
tests pass running: `go run  ./tests/e2e/...  -tc changeover`
---
I have...
I have...

test: Fix e2e tests for changeover

---

.github/workflows/docker-publish.yml

Closes: #1592 
GH workflow to publish ICS docker images
Workflow is triggerd to build
- `interchain-security:latest` image when a commit is pushed to 'main' branch
- `interchain-security:vX.Y.Z` when a tag with pattern vX.Y.Z is pushed 
- `interchain-security:vX.Y.Z-lsm` when a tag with pattern vX.Y.Z-lsm is pushed 
for all other commits/tags no docker image workflow  will be triggered
---
I have...
I have...

ci: GH workflow for publishing docker images

---

docs/docs/adrs/adr-015-partial-set-security.md

Remove the word "fraction" from the ADR because `top_N` is a `uint32` and hence corresponds directly to a percentage.
---
I have...
I have...

docs: tiny ADR fix 

---

proto/interchain_security/ccv/provider/v1/tx.proto
x/ccv/provider/client/cli/tx.go
x/ccv/provider/keeper/keeper.go
x/ccv/provider/keeper/keeper_test.go
x/ccv/provider/keeper/key_assignment.go
x/ccv/provider/keeper/key_assignment_test.go
x/ccv/provider/keeper/msg_server.go
x/ccv/provider/keeper/partial_set_security.go
x/ccv/provider/keeper/partial_set_security_test.go
x/ccv/provider/types/codec.go
x/ccv/provider/types/keys.go
x/ccv/provider/types/keys_test.go
x/ccv/provider/types/msg.go
x/ccv/provider/types/provider.pb.go
x/ccv/provider/types/tx.pb.go
x/ccv/types/events.go

Partially closes (https://github.com/cosmos/interchain-security/issues/1586).
This PR introduces:
* state to keep track of all the validators that opted in (and when they opted in);
* state keep track of validators that are are about to opt in or opt out, namely `toBeOptIn` and `toBeOptOut` respectively;
* the `MsgOptIn` and `MsgOptOut` messages.
---
I have...
I have...

feat!: introduce MsgOptIn and MsgOptOut

---

Makefile
tests/mbt/model/README.md
tests/mbt/model/ccv.qnt
tests/mbt/model/ccv_boundeddrift.qnt
tests/mbt/model/ccv_model.qnt
tests/mbt/model/ccv_pss.qnt
tests/mbt/model/ccv_pss_model.qnt
tests/mbt/model/ccv_pss_test.qnt
tests/mbt/model/ccv_sync.qnt
tests/mbt/model/ccv_test.qnt
tests/mbt/model/ccv_utils.qnt
tests/mbt/model/libraries/extraSpells.qnt
tests/mbt/model/run_invariants.sh
tests/mbt/run_invariants.sh

Closes: #1574 
Adds partial set security to the Quint model.
This PR only contains logic, tests, and sanity checks, but no invariants yet.
The invariants are becoming more subtle and harder to define, so I want to see whether to prioritise MBT or defining the invariants first.
Highlights:
* ccv_pss contains the logic for calculating the top N set. Notice it can be much simpler because I don't need synthetic updates, I just send the whole set
* in ccv.qnt, some things changed to accomodate sending the partial validator sets
---
I have...
your handle next to the …

test: MBT: Add partial set security to model (feature branch version)

---

tests/mbt/driver/core.go
tests/mbt/driver/generate_more_traces.sh
tests/mbt/driver/generate_traces.sh
tests/mbt/driver/mbt_test.go
tests/mbt/driver/stats.go

Closes: N/A
Ports changes to the driver from #1573 to the PSS feature branch
---
I have...
I have...

test: Ports key assignment to the driver on the PSS feature branch

---

testutil/keeper/mocks.go
x/ccv/provider/keeper/hooks.go
x/ccv/provider/keeper/hooks_test.go
x/ccv/provider/keeper/keeper.go
x/ccv/provider/keeper/keeper_test.go
x/ccv/types/expected_keepers.go

(together with https://github.com/cosmos/interchain-security/pull/1620) closes: #1586
Overwrites the `AfterProposalVote` hook so that we can see whether a validator votes `Yes` on a `ConsumerAdditionProposal`. Validators that vote `Yes` are automatically opted in.
Note that we had to overwrite `AfterProposalVote` because the Tally method [deletes the votes](https://github.com/cosmos/cosmos-sdk/blob/v0.47.7/x/gov/keeper/tally.go#L71) after reading them. This also makes sense; There's no reason to keep the votes around after tallying them. Therefore, we wouldn't be able to extract any information on who voted Yes after a proposal has passed through [GetVotes](https://github.com/cosmos/cosmos-sdk/blob/v0.47.7/x/gov/keeper/vote.go#L59).
---
*All items are required. Please add a note to the …

feat!: automatically opt in validators that vote Yes on consumer addition proposals

---

docs/docs/adrs/adr-005-cryptographic-equivocation-verification.md
docs/docs/features/key-assignment.md

Closes: #1589 
---
I have...
I have...

docs: update key assignment doc

---

docs/docs/adrs/adr-015-partial-set-security.md

change emphasis on top-n and opt-in, generalize beyond invalid execution when talking about attacks, whitespace formatting
Please go to the `Preview` tab and select the appropriate sub-template:

docs: Small tweaks to PSS adr for clarity

---

tests/mbt/driver/core.go
tests/mbt/driver/generate_more_traces.sh
tests/mbt/driver/generate_traces.sh
tests/mbt/driver/mbt_test.go
tests/mbt/driver/setup.go
tests/mbt/driver/stats.go
tests/mbt/model/ccv_pss_model.qnt

Closes: #1631 
* Handles new action types OptIn and OptOut
* Handles the new topN field when adding consumer chains
Some things I decided against doing:
* I think comparing the sets of opted in validators between model and system is probably unnecessary, because those will become the validator sets on the consumer chain anyways, so if there is an issue with who is opted in, this will be detected when the validator sets are eventually different.
* Starting the chain with an initial validator set different from the replicated security valset will come later, since I will want to reuse the function to compute the partial set from the keeper
---
I …

test: Add driver for PSS

---

.github/workflows/docker-publish.yml
.github/workflows/nightly-e2e.yml

Closes: #XXXX
fix GH workflow for docker images & nightly compatiblity tests
Issues:
- timeout for nightly comaptibility tests is too low. (local runs  ~ 1:10 h)
- no docker images were published for  relase/** branch
---
I have...
I have...

chore: fix GH workflow for compatiblity tests and docker images

---

.github/workflows/nightly-e2e.yml

Closes: #XXXX
replace provider image v3.3.2-lsm with v3.3.3-lsm to be checked on nightly compatibility tests
results from local run passed:
```
Summary:
- time elapsed: 1h3m6.548360583s
- 7/7 tests passed
- 0/7 tests failed
- 0/7 tests with misc status (check details)
```
I have...
I have...

ci: update provider versions on nigthly comatibility runs

---

.github/workflows/docker-publish.yml
Makefile

Closes: #XXXX
LATEST_RELEASE variable in makefile required to perform a `git fetch` to get required variable value.
This was executed for each make which is not necessary.
Fix is using 'lazy evaluation' to execute related commans only when variable is referenced.
---
I have...
I have...

build: fix make issue

---

.github/workflows/nightly-e2e.yml

Closes: #XXXX
Nighlty compatiblity tests were failing due to commit hashes not found when
tests were executing `git merge-base` commands
```
running  /usr/bin/git merge-base --is-ancestor d4dde74b062c2fded0d3b3dbef4b3b0229e317f3 v3.3.0
2024/03/06 03:03:58 Failed getting genesis transformation parameter: error identifying transform parameter 'exit status 128': fatal: Not a valid commit name d4dde74b062c2fded0d3b3dbef4b3b0229e317f3
```
Fix requests to get all history for all branches and tags
---
I have...
your handle next to the items reviewed if you only reviewed …

ci: fix nightly compatiblity tests

---

x/ccv/provider/keeper/key_assignment.go

Closes: #XXXX
---
I have...
I have...

refactor: simplify key-assignment logic

---

docs/docs/adrs/adr-014-epochs.md

Modified the epochs ADR to describe the latest epoch-implementation we decided upon (see [#1516](https://github.com/cosmos/interchain-security/issues/1516)). 
I have...
I have...

docs: modify epochs ADR to capture latest design

---

tests/integration/distribution.go
tests/integration/setup.go
testutil/ibc_testing/generic_setup.go
testutil/integration/debug_test.go

Closes: #1633
---
I have...
I have...

test: update integration test suite for PSS

---

tests/e2e/actions.go
tests/e2e/config.go
tests/e2e/main.go
tests/e2e/test_runner.go
tests/e2e/test_target.go

In e2e tests the selection of a test case with specific test config did not work as specified ("-tc testcase::testconfig").
Also when running multiple test case the TestRunner where referencing  a TestTarget, instead of having it's own instance, which caused side effects. 
Fix will provide each test runner it's own target instance.
---
I have...
I have...

test: fix e2e testcase selection

---

tests/integration/distribution.go
x/ccv/provider/keeper/distribution.go
x/ccv/provider/keeper/distribution_test.go

This PR brings the epochs into the logic of the PSS reward distribution. In particular, by using the consumers' validator set stored on the provider to allocate the consumer rewards.
Closes: #XXXX
---
I have...
I have...

feat!: complete the PSS reward distribution

---

tests/e2e/actions_consumer_misbehaviour.go

The E2E consumer misbehaviour test is currently failing during the nightly tests.
The problem is that the test isn't waiting for enough blocks to see that the validators are jailed.
Closes: #1683 
---
I have...
I have...

test: fix E2E consumer misbehaviour test

---

x/ccv/provider/client/cli/tx.go
x/ccv/provider/handler.go
x/ccv/provider/types/msg.go

Closes: #1707
---
I have...
I have...

feat!: update PSS cli

---

x/ccv/provider/keeper/proposal.go
x/ccv/provider/keeper/proposal_test.go

`ConsumerAdditionProposal`s for _opt-in_ chains that have no validator opted-in when they're initialized (i.e., when we create the consumer genesis) won't be able to start. This PR adds a check to drop proposals in those cases.
---
I have...
I have...

feat!: only perform consumer additions for non-empty chains

---

.changelog/unreleased/api-breaking/provider/1732-assigning-already-assigned-key-fix.md
.changelog/unreleased/state-breaking/provider/1732-assigning-already-assigned-key-fix.md
tests/e2e/main.go
tests/e2e/steps_compatibility.go
tests/e2e/steps_start_chains.go
tests/e2e/tracehandler_testdata/consumer-double-sign.json
tests/e2e/tracehandler_testdata/democracy.json
tests/e2e/tracehandler_testdata/democracyRewardsSteps.json
tests/e2e/tracehandler_testdata/happyPath.json
tests/e2e/tracehandler_testdata/multipleConsumers.json
tests/e2e/tracehandler_testdata/shorthappy.json
tests/e2e/tracehandler_testdata/slashThrottle.json
tests/integration/key_assignment.go
x/ccv/provider/handler_test.go
x/ccv/provider/keeper/key_assignment.go

Closes: #1731 
If a validator tries to assign the consumer key it already has assigned itself,
there previously was an error.
This changed the PR to do a noop instead.
This fixes the behaviour when opting in and specifying the consumer key that already is assigned by the validator, which previously wasn't possible.
I also got rid of two trailing newlines that produced warnings when regenerating the traces.
Note: MBT failure is currently expected
I didn't find any documentation that specifically talked about what happens when assigning the same key twice to the same validator, so I found nothing to update here specifically.
---
I have...
*All items …

fix!: Fix opt-in assignment

---

tests/mbt/model/libraries/extraSpells.qnt

This is a simple fix for the model, so it works with Apalache (`quint verify`). Apalache doesn't support non-constant values in `range`, but in this case, we can simply use `indices` to achieve the same thing and avoid the issue. The behavior on simulation should stay the same, and this unblocks usage with Apalache.
---
I have...
- [-] Provided a link to the relevant issue or specification
- There are no issues related to this. I've been fixing some other issues on the quint repo related to this, and bumped into this problem myself.
- I need authorization for running them first
*All items are required. Please add a note if the item is not applicable …

test: Quint model - Use `indices` instead of `range` to avoid problem with Apalache

---

tests/mbt/model/ccv.qnt
tests/mbt/model/ccv_test.qnt

Closes: MBT test failure in https://github.com/cosmos/interchain-security/actions/runs/8472508023/job/23214757156?pr=1740
The issue occurred if there was first a double-sign slash request and then a downtime slash request for the same node.
In the model, I mistakenly always put outstandingDowntime for the node to true, so the downtime slash request was not sent.
This PR fixes this and adds a test for the issue.
---
I have...
I have...

fix: in mbt, do not set outstandingDowntime for double-sign slashes

---

tests/integration/setup.go

Add some getters in the integrations test suite to test ICS epochs in Gaia.
Closes: #XXXX
---
I have...
I have...

test: Add getters for testing epochs in Gaia

---

tests/e2e/actions.go
tests/e2e/main.go
tests/e2e/steps_compatibility.go
tests/e2e/steps_consumer_misbehaviour.go
tests/e2e/steps_partial_set_security.go
tests/e2e/steps_sovereign_changeover.go
tests/e2e/steps_start_chains.go
tests/e2e/test_driver.go
tests/e2e/tracehandler_testdata/changeover.json
tests/e2e/tracehandler_testdata/consumer-double-sign.json
tests/e2e/tracehandler_testdata/consumer-misbehaviour.json
tests/e2e/tracehandler_testdata/democracy.json
tests/e2e/tracehandler_testdata/democracyRewardsSteps.json
tests/e2e/tracehandler_testdata/happyPath.json
tests/e2e/tracehandler_testdata/multipleConsumers.json
tests/e2e/tracehandler_testdata/shorthappy.json
tests/e2e/tracehandler_testdata/slashThrottle.json
x/ccv/provider/keeper/proposal_test.go

Closes: [#1630](https://github.com/cosmos/interchain-security/issues/1630)
Added 2 simple E2E tests: i) for an _Opt-In_ chain, and ii) for a _Top-N_ chain.
Main piece of logic to review is everything in `tests/e2e/steps_partial_set_security.go`. All other E2E tests were modified to have a `TopN == 100` to work as before.
---
I have...
I have...

test: add partial-set-security E2E tests

---

.github/workflows/docker-publish.yml

Closes: #XXXX
Image signing failed due to change of cosign changes [TUF Trust Root and client](https://blog.sigstore.dev/tuf-root-update/)
```
Error: signing [ghcr.io/cosmos/interchain-security:latest@sha256:56298a96ff435bdda4b3a490bc74c7f936934fe7348708635e0210a76c3b713a]: 
getting signer: getting key from Fulcio: 
getting CTFE public keys: updating local metadata and targets: error updating to TUF remote mirror: invalid key
```
Changing to client version >= v2.2.0 fixes signing error
Tested on fork
Also fixing: 
builds triggered on commits targeting release/** branches which were failing due to missing tag
---
I have...
*All items are required. …

ci: fix publishing docker images

---

x/ccv/provider/keeper/relay.go
x/ccv/provider/keeper/relay_test.go

**Problem**
If the provider receives a slash packet from a consumer chain for a validator `V` and `V` is not a `ConsumerValidator`, then we simply return without queueing a `SlackAck` to send back to the consumer. This could lead to having a validator that is not validating a consumer chain but the validator is not being slashed.
To see this, think of the following scenario where during epoch 0 we have validators `V0`, `V1`, and `V2` as `ConsumerValidator`s, then during epoch 1 `V0` is not a `ConsumerValidator` anymore and then `V0` is a `ConsumerValidator` during epoch 2.
Now assume, that during epoch 1, the provider receives a slash packet to slash `V0`. This could happen if the `VSCPacket` that was sent at the end of epoch 0 has not yet reached the consumer chain. Because `V0` is not …

fix!: return a SlashAck even if the validator is not a consumer validator

---

x/ccv/provider/migrations/migrator.go
x/ccv/provider/migrations/v3/migration_test.go
x/ccv/provider/migrations/v3/migrations.go
x/ccv/provider/migrations/v4/migration_test.go
x/ccv/provider/migrations/v4/migrations.go
x/ccv/provider/module.go

Epochs code changes the paramaters store, so the new parameter needs to be added to the store via a migration.
Had v4.0.0 and v4.1.0 stayed the same consensus version, provider chains using v4.0.0 would panic when migrating to v4.1.0 because of the missing migration.
To mitigate this issue provider consensus version got bumped to `4` and the migration code was refactored to introduce the `v4` migration.

fix!: introduce v4 provider migration code

---

UPGRADING.md
x/ccv/provider/module.go

This code registers a migration handler that was missing in https://github.com/cosmos/interchain-security/pull/1762.
This was discovered during upgrade testing.

fix!: register provider v3 to v4 migration handler

---

testutil/keeper/mocks.go
x/ccv/provider/keeper/hooks.go
x/ccv/provider/keeper/relay_test.go
x/ccv/types/expected_keepers.go

Note that if this solution is adopted it will require some migrations.
Closes: #1727
---
I have...
I have...

fix!: update unbonding  pausing for PSS

---

proto/interchain_security/ccv/provider/v1/query.proto
x/ccv/provider/keeper/grpc_query.go
x/ccv/provider/keeper/grpc_query_test.go

Fixes the issue described here: https://github.com/cosmos/interchain-security/issues/1251#issuecomment-2016665369
Converts QueryAllPairsValConAddrByConsumerChainID output to consumer addresses, so instead of raw bytes in gRPC/REST response we now have this:
I patched my Gaia node with this: https://api.cosmos.quokkastake.io/interchain_security/ccv/provider/consumer_chain_id?chain_id=neutron-1, seems to work more correct, also tested it with gRPC and it also works.
---
I have...
I have...

fix: fixed QueryAllPairsValConAddrByConsumerChainID output formatting

---

.github/dependabot.yml
.mergify.yml
FEATURES.md
RELEASES.md

Closes: #XXXX
---
I have...
I have...

chore: add v4.1.x to docs and cleanup bots

---

proto/interchain_security/ccv/provider/v1/query.proto
tests/integration/distribution.go
x/ccv/provider/keeper/distribution.go
x/ccv/provider/keeper/keeper.go
x/ccv/provider/types/codec.go

Address nits from #1809 and remove possible panic in BeginBlockRD due to a marshalling error in [GetConsumerCommission](https://github.com/cosmos/interchain-security/blob/8e27d284d4924afc63ca29a17f549c275c540817/x/ccv/provider/keeper/keeper.go#L1258-L1259). 
Closes: #XXXX
---
I have...
I have...

fix!: handle consumer commission marshalling errors gracefully

---

docs/README.md
docs/build_deploy.sh

Fixes issues in docs build:
```shell
git fetch origin legacy-docs-page
git checkout origin/legacy-docs-page -- legacy
* branch              legacy-docs-page -> FETCH_HEAD
error: pathspec 'legacy' did not match any file(s) known to git
cp: cannot stat './legacy': No such file or directory
```
The [legacy docs branch](https://github.com/cosmos/interchain-security/tree/legacy-docs-page) was changed to have `./docs/legacy` tree structure instead of just `./legacy`.
This was needed because the working dir of the deploy scripts is `./interchain-security/docs` instead of just `./interchain-security`

docs: update docs deployment

---

tests/e2e/state.go
tests/e2e/steps_partial_set_security.go
tests/e2e/tracehandler_testdata/changeover.json
tests/e2e/tracehandler_testdata/consumer-double-sign.json
tests/e2e/tracehandler_testdata/consumer-misbehaviour.json
tests/e2e/tracehandler_testdata/democracy.json
tests/e2e/tracehandler_testdata/democracyRewardsSteps.json
tests/e2e/tracehandler_testdata/happyPath.json
tests/e2e/tracehandler_testdata/multipleConsumers.json
tests/e2e/tracehandler_testdata/shorthappy.json
tests/e2e/tracehandler_testdata/slashThrottle.json
x/ccv/provider/keeper/grpc_query.go
x/ccv/provider/keeper/keeper.go

Closes: #1822 
Fixes an issue where the logic for has-to-validate was broken with opt-in consumer chains.
Also adds state to the e2e tests to hit this query.
---
I have...
I have...

fix: Fix has-to-validate query

---

tests/integration/slashing.go
x/ccv/provider/keeper/relay.go
x/ccv/provider/keeper/relay_test.go

Drop slashing packets for non opted-in validators before updating the slash meter, see [comment](https://github.com/cosmos/interchain-security/pull/1809#discussion_r1579405578). 
Closes: #XXXX
---
I have...
I have...

fix!: fix slashing in PSS

---

testutil/keeper/mocks.go
x/ccv/provider/keeper/distribution.go
x/ccv/provider/keeper/partial_set_security_test.go
x/ccv/types/expected_keepers.go

Validate the rate against the minimum when setting the consumer commission rate.
Note this means that the minimum for all consumers is simply the one on the provider.
I messed up the template, but it's a small PR anyways.

fix: Validate consumer commission rate against minimal rate

---

.coderabbit.yml

Closes: #XXXX
Coderabbit is really spammy on large markdown files, see https://github.com/cosmos/interchain-security/pull/1859
I think we should probably not have it run on the docs.
It's been doing ok on code imo, so I don't want to get rid of it completely, but just want to remove it from the docs specifically, since the noise-signal ratio was not very good there,
---
I have...
I have...

chore: Make coderabbit ignore docs folder

---

RELEASE_NOTES.md
RELEASE_PROCESS.md

Add a section that describes how to add new releases to docs pages.

docs: add docs section to RELEASE_PROCESS.md

---

.coderabbit.yml

After this change, the bot should only review PRs when a review is manually requested.
The command should be
```
@coderabbitai review
```
to make it review a PR you want the bot to comment on
Closes: #XXXX
---
I have...
I have...

chore: Disable coderabbit auto reviews

---

x/ccv/provider/keeper/relay.go
x/ccv/provider/keeper/relay_test.go
x/ccv/provider/keeper/validator_set_storage.go

Closes: #XXXX
- remove panic from `getTotalPower`
- remove panics from `EndBlockVSU`
---
I have...
I have...

fix!: handle some panics

---

x/ccv/provider/migrations/v8/migrations.go

**Problem**
Top N was not correctly set for already launched chains during migrations. We also had the same issue for other power-shaping parameters. Issue was that we did not create the store keys correctly.
**Solution**
Use the length of the `chainId` to create the right keys when doing the migration. This PR presents a rudimentary solution because we did not go thoroughly through all the keys. The reason we are publishing this PR as is, with no testing, is to unblock as soon as possible the teams behind Hypha and Forge.
I have...
your handle next to the items …

fix!: fix migration issue

---

proto/interchain_security/ccv/provider/v1/query.proto
tests/mbt/driver/core.go
tests/mbt/driver/mbt_test.go
x/ccv/provider/client/cli/tx.go
x/ccv/provider/types/msg.go
x/ccv/provider/types/query.pb.go

Both consumer misbehaviour and equivocation evidence CLI commands are missing a [consumer-id] argument to work as expected.
Closes: #XXXX
---
I have...
I have...

fix: fix misbehaviour and equivocation evidence CLI commands

---

x/ccv/provider/types/msg.go
x/ccv/provider/types/msg_test.go

Closes: #XXXX
This was fixed in v5.2.0. This PR brings the fix to main and therefore it doesn't need changelog entries. 
---
I have...
I have...

fix!: add message validation of signers (bring fix to main)

---

x/ccv/provider/client/cli/tx.go

Closes: #XXXX
---
I have...
I have...

chore: update TX CLI help

---

x/ccv/provider/keeper/consumer_lifecycle.go
x/ccv/provider/keeper/consumer_lifecycle_test.go
x/ccv/provider/keeper/msg_server.go
x/ccv/provider/types/errors.go
x/ccv/provider/types/msg.go
x/ccv/provider/types/msg_test.go

Closes: #XXXX
---
I have...
I have...

fix!: replace CanLaunch with InitializeConsumer

---

tests/e2e/actions.go
tests/e2e/config.go
tests/e2e/main.go
tests/e2e/state.go
tests/e2e/steps_partial_set_security.go
tests/e2e/steps_permissionless_ics.go
tests/e2e/steps_start_chains.go
tests/e2e/test_runner.go
tests/e2e/testnet-scripts/start-chain.sh

Add basic e2e tests for permissionless ICS
Change e2e tests to allow chain configurations with same ChainID
Limitation:
Current hermes version does not support two chains with same 'ChainID'. Therefore the tests Initializes two
chains with same ChainID and launches only one of them.
---
I have...
I have...

test: Add e2e tests for permissionless ICS

---

x/ccv/provider/keeper/consumer_lifecycle.go
x/ccv/provider/keeper/partial_set_security.go
x/ccv/provider/keeper/partial_set_security_test.go
x/ccv/provider/keeper/relay.go

Closes: #XXXX
---
I have...
I have...

fix!: make OptInTopNValidators return an error

---

tests/e2e/actions.go
tests/e2e/config.go
tests/e2e/test_runner.go

The slashing window param was too small and caused the e2e-test `stepsAssignConsumerKeyOnStartedChain` to fail randomly.

test:  extend slashing window in E2E-tests

---

tests/integration/slashing.go
x/ccv/provider/keeper/grpc_query.go
x/ccv/provider/keeper/relay.go

**Problem**
See [comment](https://github.com/cosmos/interchain-security/pull/2262#discussion_r1758467682). There's no reason why a validator would have to validate a stopped chain.
**Solution**
Change `hasToValidate` so queries return correct whether a validator has to validate.
Also, modified jailing code so that from the moment a chain stops until it gets deleted, we cannot jail a validator for downtime. 
---
I have...
I have...

fix!: only validate active chains

---

.changelog/unreleased/bug-fixes/2282-duplicate-events.md
x/ccv/consumer/keeper/distribution.go
x/ccv/provider/keeper/consumer_lifecycle.go

Closes: #XXXX
`CacheContext` already automatically emits events on the parent context's EventManager when the caller executes the `writeCache`. 
---
I have...
I have...

fix!: remove duplicate event emission

---

contrib/local-testnet.sh

Add a local testnet script which spins a `TopN` consumer with a few nodes.

test: add local testnet script for permissionless ICS

---

x/ccv/provider/client/cli/query.go

Fix `nil` pointer error in the `list-consumer-chains` query.
Closes: #XXXX
---
I have...
I have...

fix: fix `list-consumer-chains` CLI command 

---

.changelog/unreleased/improvements/2357-init-params.md
.changelog/unreleased/state-breaking/2357-init-params.md
Dockerfile
Dockerfile.combined
tests/e2e/actions.go
testutil/keeper/unit_test_helpers.go
x/ccv/provider/keeper/consumer_lifecycle_test.go
x/ccv/provider/keeper/grpc_query_test.go
x/ccv/provider/keeper/msg_server.go
x/ccv/provider/keeper/msg_server_test.go
x/ccv/provider/keeper/permissionless.go
x/ccv/provider/keeper/permissionless_test.go
x/ccv/provider/types/msg.go
x/ccv/provider/types/msg_test.go
x/ccv/provider/types/provider.go
x/ccv/types/params.go

Closes: #XXXX
---
I have...
I have...

fix!: validate initial height and set default values for init consumer params 

---

.changelog/unreleased/bug-fixes/2363-zero-rewards.md
.changelog/unreleased/state-breaking/2363-zero-rewards.md
x/ccv/provider/keeper/distribution.go

Closes: #XXXX
---
I have...
I have...

fix!: add check for zero rewards

---

docs/docs/build/modules/02-provider.md
docs/docs/consumer-development/onboarding.md
x/ccv/provider/client/cli/tx.go

Closes: #XXXX
---
I have...
I have...

docs: update onboarding guidelines

---

tests/integration/setup.go
testutil/ibc_testing/generic_setup.go

During the testing [setup](https://github.com/cosmos/interchain-security/blob/acbc4c787d7c3a86ee8956b5c9670df1a570ddf1/tests/integration/setup.go#L153-L154), some consumer keys are assigned to the first consumer chain. This is achieved by calling the [preProposalKeyAssignment](https://github.com/cosmos/interchain-security/blob/acbc4c787d7c3a86ee8956b5c9670df1a570ddf1/tests/integration/setup.go#L154) function with the  `FirstConsumerId` global variable. However, this variable is only initiated later in [AddConsumer](https://github.com/cosmos/interchain-security/blob/acbc4c787d7c3a86ee8956b5c9670df1a570ddf1/testutil/ibc_testing/generic_setup.go#L158-168). As a result, the keys are mapped to an empty `string` `""` as the consumerId, causing tests that rely on these consumer keys, e.g. …

test: fix key assignment in testing

---

docs/docs/build/modules/02-provider.md
docs/docs/build/modules/03-consumer.md

chore: fix typos

---

app/consumer-democracy/app.go
tests/e2e/testnet-scripts/start-changeover.sh

This makes the dummy consumer-democracy-cdd binary more flexible. It's really useful for testing sovereign to consumer changeovers.
---
I have...

fix: make consumer-democracy read the sovereign genesis from nodeHome

---

scripts/test_doc/test_documentation.md
tests/integration/democracy.go
tests/integration/unbonding.go
testutil/integration/debug_test.go
x/ccv/consumer/keeper/changeover.go
x/ccv/consumer/keeper/validators.go
x/ccv/consumer/keeper/validators_test.go

Closes: https://github.com/cosmos/interchain-security/issues/1245

feat!: enable unjail on pre-ccv chains

---

tests/integration/unbonding.go

Fixes test failures in democ test suite when `TestConsumerUnjailNoOp` is run.
This test would always fail for democ test suite because the standalone staking keeper is always available.

test: test unjail ops only when standalone staking is not available
