cosmos/interchain-security

go.mod, go.sum, x/ccv/provider/keeper/keeper.go, x/ccv/provider/keeper/relay.go, x/ccv/provider/provider_test.go, x/ccv/provider/unbonding_hook_test.go, x/ccv/types/expected_keepers.go
Minor naming update to be based on the [interchain-security-rebase](https://github.com/cosmos/cosmos-sdk/tree/interchain-security-rebase) cosmos-sdk branch.
=> Update Cosmos-SDK import

x/ccv/consumer/keeper/relay.go, x/ccv/provider/keeper/relay.go, x/ccv/utils/utils.go
Closes https://github.com/cosmos/interchain-security/issues/57
Instead of https://github.com/cosmos/interchain-security/pull/76 due to the renaming from https://github.com/cosmos/interchain-security/pull/75
=> Create single send function

x/ccv/consumer/keeper/validators.go, x/ccv/consumer/keeper/validators_test.go
Fixes
- https://github.com/cosmos/interchain-security/issues/105
=> Ensure ValidatorUpdate aggregation on consumer side does not trigger panic

.github/workflows/automated-tests.yml
Renamed to better reflect meaning
=> Renames integration tests action to automated tests

README.md
Solves
- https://github.com/cosmos/interchain-security/issues/175
=> Fix #175 delete outdated parts of the readme

.github/workflows/codeql.yml
See
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql
inspired by gaia
=> Adds codeql github action

.github/workflows/build.yml
Partially solves
- https://github.com/cosmos/interchain-security/issues/196
Thanks @marbar3778 !
=> Adds sonar action

go.mod, go.sum
Closes https://github.com/cosmos/interchain-security/issues/200
- https://github.com/cosmos/interchain-security/issues/200
=> Upgrade to 1.18

sonar-project.properties
The final step in configuration sonarcloud to work on PRs and provide coverage ect.
I also disabled the automatic analysis which is what we've had until now, and is somewhat annoying.
=> Adds sonar-project.properties

.github/workflows/build.yml, sonar-project.properties
This will let us see a detailed coverage report and include a coverage badge.
=> Adds coverage to sonar workflow

app/provider/app.go, go.mod, go.sum, x/ccv/provider/stop_consumer_test.go, x/ccv/provider/unbonding_test.go
Bump dependencies to track latest (see [here](https://github.com/cosmos/cosmos-sdk/tree/846d0158765e3c94edc4dc038a697b9247932bd5))
https://github.com/cosmos/cosmos-sdk/commits/interchain-security-rebase
Fixes https://github.com/cosmos/interchain-security/issues/270
=> Track latest changes to cosmos-sdk (@846d01)

e2e-tests/slashing_test.go, x/ccv/provider/keeper/keeper.go, x/ccv/provider/keeper/keeper_test.go, x/ccv/provider/keeper/relay.go
fixes https://github.com/cosmos/interchain-security/issues/296
=> Cleanup related to #296

Dockerfile, e2e-tests/common_test.go, e2e-tests/unbonding_test.go, e2e-tests/valset_update_test.go, integration-tests/actions.go, integration-tests/main.go, integration-tests/steps.go, integration-tests/testnet-scripts/start-chain.sh
Closes https://github.com/cosmos/interchain-security/issues/255, also adds a corresponding e2e test
=> Redelegation integration tests

README.md, app/consumer-democracy/app.go, app/consumer/app.go, app/provider/app.go, tests/e2e/README.md, tests/e2e/channel_init.go, tests/e2e/common.go, tests/e2e/democracy.go, tests/e2e/distribution.go, tests/e2e/instance_test.go, tests/e2e/normal_operations.go, tests/e2e/setup.go, tests/e2e/slashing.go, tests/e2e/stop_consumer.go, tests/e2e/unbonding.go, tests/e2e/valset_update.go, testutil/e2e/interfaces.go
@mpoke here's fixes to the merge conflicts for #406 
This PR diff is correct if it makes no meaningful functionality changes to your PR
=> Fix init timeout conflicts

x/ccv/provider/types/keys.go
Addresses https://github.com/cosmos/interchain-security/pull/422#discussion_r1011606526
Edit: Closes https://github.com/cosmos/interchain-security/issues/423
=> copy -> append in provider key definitions

docs/quality_assurance.md
Used NA as nothing is planned for these items.
=> Update QA markdown software engineering concerns

.github/CODEOWNERS, x/ccv/consumer/ibc_module.go, x/ccv/consumer/keeper/distribution.go, x/ccv/consumer/keeper/relay.go, x/ccv/provider/keeper/keeper.go, x/ccv/provider/keeper/proposal.go, x/ccv/provider/keeper/relay.go, x/ccv/types/events.go
commit 5dc2bbf7ad64b0286f3665a0433aa51e90606719
Author: MSalopek <35486649+MSalopek@users.noreply.github.com>
Date:   Fri Nov 11 20:03:22 2022 +0100
add event emissions to provider and consumer (#427)
* add todos for event emissions
* introduce ccv_consumer_added, ccv_fee_channel_opened events
* add vsc_first_packet event in consumer
* add fee distribution event; small refactor
* add slash request events
* add pending slash request clearing events
* move all events to ccv; add CreateClient event on provi
* remove event addition TODO tags
* update after reviews
* small refactors
* address review comments and refactor
Co-authored-by: Daniel T <30197399+danwt@users.noreply.github.com>
commit 8d158d9965c37d50c224a9afc8224ed9b2f8f84f
Author: Shawn Marshall-Spitzbart …
=> Squashed commit of the following:

tests/difference/core/driver/core_test.go, tests/e2e/stop_consumer.go, x/ccv/consumer/keeper/genesis.go, x/ccv/consumer/keeper/genesis_test.go, x/ccv/consumer/keeper/keeper.go, x/ccv/consumer/keeper/keeper_test.go, x/ccv/provider/keeper/genesis.go, x/ccv/provider/keeper/grpc_query.go, x/ccv/provider/keeper/hooks.go, x/ccv/provider/keeper/keeper.go, x/ccv/provider/keeper/keeper_test.go, x/ccv/provider/keeper/proposal.go, x/ccv/provider/keeper/proposal_test.go, x/ccv/provider/keeper/relay.go
Closes https://github.com/cosmos/interchain-security/issues/449, https://github.com/cosmos/interchain-security/issues/446
=> Make iterators consistent with SDK pattern 

x/ccv/provider/keeper/proposal.go
Closes https://github.com/cosmos/interchain-security/issues/443
=> Resolve +-1 question mark in MakeConsumerGenesis

.github/PULL_REQUEST_TEMPLATE/base_template.md
Adds pull request template to repo.
Closes: #398.
=> add pull request template

proto/interchain_security/ccv/provider/v1/provider.proto, x/ccv/provider/keeper/proposal.go, x/ccv/provider/proposal_handler.go, x/ccv/provider/types/provider.pb.go
=> add consumer addition proposal documentation

app/consumer/app.go
=> fix: remove duplicated SlashingKeeper in consumer app.go

testutil/keeper/expectations.go, x/ccv/consumer/keeper/genesis_test.go, x/ccv/provider/client/handler_test.go, x/ccv/provider/keeper/genesis_test.go, x/ccv/provider/keeper/msg_server.go
* Fix broken expectations in consumer genesis tests
* Update provider genesis tests
=> fix: key assignment genesis tests

x/ccv/provider/keeper/key_assignment.go, x/ccv/provider/keeper/key_assignment_test.go
Adds some unit tests and random testing. It's a bit unfinished, the slash query isn't properly checked yet and the code is unpolished. But it's something.
Tests:
- assignment specific cases
- random assignents interleaved with applying mapping to random updates
- pruning property
- validator set replication
Does not test:
- Reverse lookup for slashing
=> Adds some very basic random testing and unit tests

tests/e2e/slashing.go, tests/integration/state.go
Fix `TestRelayAndApplySlashPacket` e2e test
=> fix commented TestRelayAndApplySlashPacket test

x/ccv/consumer/ibc_module.go, x/ccv/provider/ibc_module.go
Do not pass non-determinsitic error message to `NewErrorAcknowledgement`
Closes: https://github.com/cosmos/interchain-security/issues/590
=> NewErrorAcknowledgement with non-determinsitic error message

tests/integration/actions.go, tests/integration/config.go, tests/integration/main.go, tests/integration/state.go, tests/integration/steps.go, tests/integration/steps_submit_equivocation_proposal.go
Added integration test for equivocation proposal.
**NOTE** Be sure to merge #703 first.
Adds integration tests for PR #703 
All previous test pass with no issues.
=> add integration tests for equivocation proposals

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/epic-template.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/issue-template.md, .github/ISSUE_TEMPLATE/protocol-change-request.md
=> Update issue templates

CHANGELOG.md
Updates the `v1.1.x` branch with a changelog entry
Closes: #821
n/a
n/a
=> Update changelog v1.1.x

tests/e2e/step_delegation.go
Clarifies godocs on a function (not more than a nit)
If `Refactor`, describe the new or existing tests that verify no behavior was changed or added where refactors were introduced.
If `Feature` or `Fix`, describe the new or existing tests that verify the new behavior is correct and expected.
=> nit: fix description of stepsUnbond

.github/workflows/linkchecker.yml, Dockerfile, Dockerfile.gaia, docs/docs/consumer-development/onboarding.md, docs/docs/frequently-asked-questions.md
=> Merge main into feat/upgrade-ics-sdk47-ibc7

.github/workflows/golangci-lint.yml, Makefile
Due to erronous lint failures with the latest golangci-lint version, hardcode the most recent working version
v1.52.2.
---
I have...
I have...
=> chore: Hardcode golangci-lint version

docs/docs/validators/overview.md
Partially closes https://github.com/cosmos/gaia/issues/2569
Do not merge until proposal [#797](https://www.mintscan.io/cosmos/proposals/797) closes on 2023-06-13 06:31:47
---
I have...
I have...
=> docs: Increase the validator set of cosmos hub to 180 from 175

.github/dependabot.yml, .mergify.yml
Closes: NA
Enable mergify to backport PR to `release/v2.0.x` branch.
Also, enable security dependencies for `release/v2.0.x` branch.
---
I have...
I have...
=> chore: enable mergify

sonar-project.properties
Closes: NA
Remove `docs/**`, `app/**` , `cmd/**` from SonarCloud coverage analysis. 
---
I have...
I have...
=> ci: update sonar.exclusions

CHANGELOG.md
Closes: NA
---
I have...
I have...
=> docs: add v3.0.0 changelog

.github/workflows/proto.yml
Closes: #1099
Remove proto linting since we cannot change much about it. The linter is just creating noise.
---
I have...
I have...
=> chore: remove noisy proto linter

CHANGELOG.md
Update changelog to include note about fixing SlashPacket compatibility over the Wire
Please go the the `Preview` tab and select the appropriate sub-template:
=> chore: update CHANGELOG.md for v3

CHANGELOG.md
Closes: NA
Update `release/v3.0.x` changelog:
* add #1119 to `[UNRELEASED]` section
---
I have...
I have...
=> chore: add cometbft bump PR info to changelog

docs/docs/adrs/adr-template.md, docs/docs/consumer-development/consumer-chain-governance.md, docs/docs/consumer-development/onboarding.md, docs/docs/features/key-assignment.md, docs/docs/features/proposals.md, docs/docs/features/slashing.md, docs/docs/introduction/terminology.md
=> docs: fix typos

docs/docs/adrs/adr-005-cryptographic-equivocation-verification.md
This will fix the link check test that's failing in CI
I have...
I have...
=> chore: fix link in recent ADR

docs/docs/frequently-asked-questions.md
Closes: #1166 
This PR adds information to the `./docs/docs/frequently-asked-questions.md` document specifying which versions of the Go relayer have support for the CCV module.
---
I have...
I have...
=> docs: update supported relayers section in faq

CHANGELOG.md
Closes: NA
---
I have...
I have...
=> docs: add v2.0.0-lsm changelog section

CHANGELOG.md
Closes: NA
Cleanup changelog after [separating releases](https://github.com/cosmos/interchain-security/pull/1217).
---
I have...
I have...
=> docs: cleanup changelog

CHANGELOG.md
Updates CHANGELOG.md for `v3.2.0-consumer` release, the first release that follows new semver rules. 
Related to https://github.com/cosmos/interchain-security/issues/1198
I have...
I have...
=> docs: update CHANGELOG.md for `v3.2.0-consumer` release

.github/dependabot.yml, .mergify.yml
Closes: NA
---
I have...
I have...
=> ci: update mergify and dependabot for v2.x-lsm

.github/dependabot.yml, .mergify.yml
Closes: NA
---
I have...
I have...
=> ci: update bots for v2.1.x-provider-lsm

CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
=> doc: add changelog entry for v2.*-lsm releases

app/consumer/abci.go, app/consumer/app.go, app/consumer/export.go, app/provider/app.go, cmd/interchain-security-cd/cmd/root.go, cmd/interchain-security-cd/main.go, cmd/interchain-security-pd/cmd/root.go, x/ccv/consumer/keeper/hooks.go, x/ccv/consumer/keeper/keeper.go, x/ccv/consumer/keeper/params.go, x/ccv/consumer/keeper/validators.go, x/ccv/types/expected_keepers.go
Update consumer application for v50 on the feature branch.
Closes: #1352
=> consumer: update consumer app v50 and make buildable

CHANGELOG.md
Please go the the `Preview` tab and select the appropriate sub-template:
=> doc: update CHANGELOG for v2.2.0-provider-lsm release

CHANGELOG.md
Please go the the `Preview` tab and select the appropriate sub-template:
=> doc: update CHANGELOG for v2.3.0-provider-lsm release

.changelog/v3.2.0/features/provider/1280-reward-denoms.md, .changelog/v3.2.0/state-breaking/provider/1280-reward-denoms.md, CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
=> docs: add entry for reward denom proposal

CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
=> docs: add v2.3.0-provider-lsm section to CHANGELOG

CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
=> docs: add v2.4.0-lsm section to changelog

x/ccv/provider/client/cli/tx.go
Closes: #XXXX
---
I have...
I have...
=> fix: update consumer double vote cmd

CHANGELOG.md
Closes: NA
---
I have...
I have...
=> docs: add changelog entry for #1439

CHANGELOG.md
Closes: #XXXX
---
I have...
I have...
=> docs: backport v2 changelog sections to main

docs/docs/adrs/adr-003-equivocation-gov-proposal.md, docs/docs/adrs/adr-007-pause-unbonding-on-eqv-prop.md, docs/docs/adrs/adr-011-improving-test-confidence.md, docs/docs/adrs/adr-013-equivocation-slashing.md, docs/docs/adrs/intro.md
Closes: #XXXX
---
I have...
I have...
=> docs: reject ADR-007

tests/e2e/state.go, x/ccv/provider/keeper/relay_test.go
Closes: #XXXX
---
I have...
I have...
=> chore: fix linter

.github/pr_labeler.yml, .github/workflows/pr_labeler.yml
Closes: NA
Update the config file for https://github.com/actions/labeler as required by the latest version, i.e., https://github.com/actions/labeler/releases/tag/v5.0.0  
---
I have...
I have...
=> ci: update PR labeler config file

.github/workflows/deploy-docs.yml
Closes: #XXXX
Fix docs deployment deps and workflows.
Confirm it works:
* https://msalopek.github.io/interchain-security/
* https://github.com/MSalopek/interchain-security/actions/runs/7103573872/job/19336582819
---
I have...
I have...
=> chore: fix docs deps and deploy workflow

.github/workflows/test.yml
Closes: #XXXX
Trigger tests in the CI only when production code is modified. 
---
I have...
I have...
=> ci: add condition for e2e CIs

docs/docs/features/proposals.md
This PR fixes typos in the codebase.
Please review it, and merge if everything is fine.
If there are proto changes, run `make proto-gen` and commit the changes.
=> chore: fix spelling errors

x/ccv/provider/client/cli/tx.go, x/ccv/provider/types/codec.go
Fix the unmarshalling of consumer misbehaviour from `json` files in the the `NewSubmitConsumerMisbehaviourCmd` of the provider module client. 
First, the misbehaviour `json` file wasn't properly opened, and second, the required IBC misbehaviour type wasn't registered to the provider's codec `InterfaceRegistry`.
---
I have...
I have...
=> fix: `submit-consumer-misbehaviour` command in the provider module CLI

tests/mbt/driver/common.go, tests/mbt/driver/core.go, tests/mbt/driver/mbt_test.go, tests/mbt/driver/setup.go, testutil/simibc/chain_util.go, testutil/simibc/relay_util.go
Closes: N/A
Context in title
---
I have...
I have...
=> test: Upgrade tests/mbt and testutil/simibc

FEATURES.md, RELEASES.md
Closes: NA
- also mark `v2.1.0-provider-lsm` as EOL
---
I have...
I have...
=> docs: mark the v1 line as EOL

.changelog/epilogue.md, CHANGELOG.md, UPGRADING.md
Closes: NA
---
I have...
I have...
=> docs: fix broken links due to migration

.changelog/unreleased/api-breaking/consumer/1458-consumer-genesis-cli-fix.md, .changelog/unreleased/bug-fixes/1458-consumer-genesis-cli-fix.md
Closes: NA
Add changelog entry for #1458 
---
I have...
I have...
=> docs: add changelog entry for #1458

UPGRADING.md
Closes: #XXXX
---
I have...
I have...
=> docs: update upgrading instructions

docs/docs/validators/joining-testnet.md, docs/docs/validators/overview.md
I've found that some links in `.md` files are broken due to docs structure change. I this PR I fixed all affected links while maintaining the context of each link.
---
I have...
I have...
=> docs: update broken links to docs

Dockerfile.gaia, Makefile
Update gaia e2e testing requirements.
* add gaia with cometmock
Related: https://github.com/cosmos/gaia/issues/2866
=> test: update e2e gaia dockerfile; add gaia with cometmock

Dockerfile, Dockerfile.combined
Closes: NA
---
I have...
I have...
=> test: bump Hermes to v1.8.0 in Docker files

TESTING.md
Closes: #XXXX
Updated Testing docs with section for compatiblity tests
---
I have...
I have...
=> docs: Added compatiblity tests to docs

tests/e2e/builder.go, tests/e2e/test_target.go, tests/mbt/driver/mbt_test.go
-- DO NOT MERGE --
This PR rebases the `feat/partial-set-security` branch with `main`. To make the reviewing easier,  this PR is currently targeting the `main` branch. However, this PR's branch is intended to replace the current `feat/partial-set-security` upstreamed branch using a `git push -f`.
Note that using a merge wasn't a viable option since `feat/partial-set-security` is currently a `v4.0.0` fork.
=> chore: rebase PSS branch with main

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/epic-template.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/issue-template.md, .github/ISSUE_TEMPLATE/protocol-change-request.md
Closes: #XXXX
---
I have...
I have...
=> chore: update labels in issue templates

.github/dependabot.yml, .mergify.yml
Closes: NA
---
I have...
I have...
=> chore: add v4.1.x and v4.1.x-lsm to mergify and dependabot

x/ccv/provider/migrations/migrator.go, x/ccv/provider/migrations/v3/migration_test.go, x/ccv/provider/migrations/v3/migrations.go, x/ccv/provider/types/params.go
Closes: #1756 
This PR adds missing migration for `BlocksPerEpoch` and fixes the bugs found in upgrade tests.
---
I have...
I have...
=> fix: add missing migration; use correct constant types

RELEASE_NOTES.md, RELEASE_PROCESS.md
Closes: #XXXX
---
I have...
I have...
=> docs: update release process

UPGRADING.md
Updated `UPGRADING.md` on upgrading from `v4.0.x` to `v4.1.x` or `v4.1.x-lsm`.
---
I have...
I have...
=> docs: on upgrading from v4.0.x to v4.1.x or v4.1.x-lsm

tests/e2e/steps_partial_set_security.go
Closes: #1751 
This PR adds a test to cover the reported issue.
---
I have...
I have...
=> test: Expand PSS e2e test to include slashing

.github/ISSUE_TEMPLATE/01-bug-report.yml, .github/ISSUE_TEMPLATE/02-feature-request.yml, .github/ISSUE_TEMPLATE/03-docs-request.yml, .github/ISSUE_TEMPLATE/04-epic-template.md
Closes: #XXXX
---
I have...
I have...
=> chore: fix issue templates

Makefile, app/consumer/genesis.go, app/consumer/genesis_test.go, app/sovereign/app.go, tests/e2e/actions.go, tests/e2e/builder.go, tests/e2e/config.go, tests/e2e/main.go, tests/e2e/steps_compatibility.go, tests/e2e/test_runner.go, tests/e2e/test_target.go, tests/integration/soft_opt_out.go, tests/mbt/driver/core.go, tests/mbt/driver/mbt_test.go, testutil/integration/validators.go, testutil/simibc/relay_util.go, x/ccv/consumer/keeper/soft_opt_out.go, x/ccv/consumer/migrations/v2/migration_test.go, x/ccv/provider/client/cli/query.go, x/ccv/provider/keeper/grpc_query_test.go, x/ccv/provider/keeper/key_assignment_test.go, x/ccv/provider/keeper/proposal.go, x/ccv/provider/keeper/relay_test.go, x/ccv/provider/keeper/validator_set_update.go, x/ccv/provider/keeper/validator_set_update_test.go, x/ccv/provider/migrations/v3/migration_test.go, x/ccv/provider/migrations/v3/migrations.go, x/ccv/provider/migrations/v4/migrations.go, x/ccv/provider/types/codec.go
Closes: #XXXX
make sure that `make format` passes 
---
I have...
I have...
=> refactor: linting 

UPGRADING.md
Closes: #XXXX
---
I have...
I have...
=> docs: Add epoch migration to UPGRADING.md

docs/docs/upgrading/_category_.json, docs/docs/upgrading/migrate_v4_v5.md, docs/internal/migrations/cosmos-sdk-v0.50-migration.md, x/ccv/provider/keeper/legacy_proposal.go
=> docs: add v5 migration instructions

.github/dependabot.yml, .mergify.yml
=> chore: add release/v5.x bots targets

proto/interchain_security/ccv/provider/v1/query.proto
Please go to the `Preview` tab and select the appropriate sub-template:
=> fix: update queries REST path for PSS

.github/dependabot.yml, .mergify.yml
Closes: #XXXX
---
I have...
I have...
=> chore: add v5.0.x-provider and v5.0.x-provider to mergify and dependabot

.github/dependabot.yml, .mergify.yml
=> chore: rm v5-provider; add v4.2.0; rm old versions

testutil/keeper/expectations.go, x/ccv/provider/keeper/proposal.go, x/ccv/provider/keeper/proposal_test.go
Closes: NA
Remove redundant code from MakeConsumerGenesis
cc @p-offtermatt @insumity 
---
I have...
I have...
=> refactor: remove redundant code from MakeConsumerGenesis

.changelog/unreleased/bug-fixes/provider/1946-get-consumer-chains.md, tests/mbt/driver/core.go, tests/mbt/driver/mbt_test.go, x/ccv/provider/keeper/distribution.go, x/ccv/provider/keeper/genesis.go, x/ccv/provider/keeper/grpc_query.go, x/ccv/provider/keeper/grpc_query_test.go, x/ccv/provider/keeper/hooks.go, x/ccv/provider/keeper/keeper.go, x/ccv/provider/keeper/keeper_test.go, x/ccv/provider/keeper/partial_set_security.go, x/ccv/provider/keeper/relay.go, x/ccv/provider/migrations/v3/migrations.go, x/ccv/provider/migrations/v5/migrations.go
Backport #1946 to the PSS v50 feature branch.
=> chore!: backport #1946 (GetAllConsumerChains fix) to `feat/pss-upgrade-v50` branch

.github/workflows/nightly-e2e.yml, tests/e2e/config.go, tests/e2e/main.go, tests/e2e/steps_active_set_changes.go
backport #1942
---
I have...
I have...
=> test: backport #1942

x/ccv/provider/keeper/hooks.go
Please go to the `Preview` tab and select the appropriate sub-template:
=> chore: align to LSM hook signature to SDK v0.50.0

x/ccv/provider/types/codec.go
**Problem**
@fastfadingviolets got the following error during migration:
```
3:43PM ERR error in proxyAppConn.FinalizeBlock err="migrating ICS legacy proposals during migration: iterating through proposals: no concrete type registered for type URL /interchain_security.ccv.provider.v1.ConsumerModificationProposal against interface *v1beta1.Content" module=consensus
```
when submitting via `submit-legacy-proposal consumer-modification`.
**Solution**
(thanks to @MSalopek) registering the implementations.
---
I have...
your handle next to the items reviewed if you …
=> fix!: register `ConsumerModificationProposal` and others

.changelog/unreleased/dependencies/2200-bump-comet.md, .changelog/unreleased/dependencies/2200-bump-sdk.md
Closes: #XXXX
---
I have...
I have...
=> docs: add missing changelog entries

x/ccv/provider/client/cli/tx.go
Closes: #XXXX
---
I have...
I have...
=> fix: improve commands' description

cmd/interchain-security-cd/cmd/root.go, cmd/interchain-security-cdd/cmd/root.go, cmd/interchain-security-pd/cmd/root.go, cmd/interchain-security-sd/cmd/root.go
Fix issue caused by v0.50.9 cosmos upgrade.
=> fix: update keyring; make install fix

x/ccv/provider/migrations/v8/migrations.go, x/ccv/provider/migrations/v8/migrations_test.go
Closes: #XXXX
---
I have...
I have...
=> test: introduce checks for the migration of launched chains

.changelog/unreleased/api-breaking/provider/2171-permissionless-ICS.md.md, .changelog/unreleased/features/provider/2171-permissionless-ICS.md.md
Closes: #XXXX
Add changelog entries for Permissionless ICS notably API changes.
TODO: fix links once #2171 is merged.
---
I have...
I have...
=> docs: update changelog for Permissionless ICS 

UPGRADING.md, x/ccv/provider/migrations/v8/migrations.go
Closes: #XXXX
---
I have...
I have...
=> fix!: add metadata and init params default during permissionless migration 

x/ccv/provider/types/msg.go, x/ccv/provider/types/msg_test.go
Closes: #XXXX
---
I have...
I have...
=> fix: disallow the creation of chains that use chain ids of existing running chains

x/ccv/provider/keeper/consumer_lifecycle.go, x/ccv/provider/keeper/msg_server.go, x/ccv/provider/keeper/params.go, x/ccv/provider/types/errors.go, x/ccv/provider/types/msg.go
Closes: #XXXX
---
I have...
I have...
=> fix: address comments from permissionless review

testutil/keeper/expectations.go, testutil/keeper/unit_test_helpers.go, x/ccv/provider/keeper/consumer_lifecycle.go, x/ccv/provider/keeper/consumer_lifecycle_test.go, x/ccv/provider/keeper/keeper_test.go, x/ccv/provider/keeper/relay.go, x/ccv/provider/keeper/validator_set_update.go, x/ccv/provider/types/events.go
Closes: #XXXX
---
I have...
I have...
=> refactor: simplify LaunchConsumer logic

.github/dependabot.yml, .mergify.yml
Closes: #XXXX
---
I have...
I have...
=> chore: update mergify and dependabot

x/ccv/provider/keeper/consumer_lifecycle.go, x/ccv/provider/keeper/consumer_lifecycle_test.go, x/ccv/provider/keeper/msg_server.go
Closes: #XXXX
---
I have...
I have...
=> fix!: enable consumer to be relaunched after failed attempt

FEATURES.md, RELEASES.md
Closes: #XXXX
---
I have...
I have...
=> docs: add v6.0.0 to releases.md

.github/dependabot.yml, .mergify.yml
Closes: #XXXX
---
I have...
I have...
=> chore: add v4.5.x to dependabot and mergify

.github/dependabot.yml, .mergify.yml
Closes: #XXXX
---
I have...
I have...
=> chore: replace v6.0.x with v6.1.x for dependabot and mergify

x/ccv/provider/ibc_middleware.go, x/ccv/provider/keeper/distribution.go
Add the patch enabling the distribution of Stride consumer rewards, initially introduced by https://github.com/cosmos/interchain-security/pull/2288. 
Closes: #XXXX
---
I have...
I have...
=> feat!: add stride consumer reward patch back

docs/docs/build/modules/04-democracy.md
Closes: #XXXX
---
I have...
I have...
=> docs: fix broken link

Dockerfile, tests/e2e/test_runner.go
The E2E-tests fail randomly due to a parsing error in Hermes.
This PR solves this using a **temporary** patched version of Hermes.
---
I have...
I have...
=> test: fix e2e-tests flakiness

x/ccv/provider/client/cli/tx.go
Closes: #XXXX
---
I have...
I have...
=> docs: improve CLI help messages

x/ccv/provider/keeper/distribution.go
Add a check to consumer distribution logic to return early when there are no rewards allocated.
Closes: #XXXX
---
I have...
I have...
=> refactor: clean distribution logs

docs/docs/build/modules/02-provider.md, docs/docs/build/modules/03-consumer.md, docs/docs/consumer-development/changeover-procedure.md, docs/docs/consumer-development/onboarding.md, x/ccv/provider/client/cli/tx.go
Closes: #XXXX
---
I have...
I have...
=> docs: update docs

x/ccv/provider/keeper/consumer_equivocation.go
The purpose here should be to initialize a slice with a capacity of  len(byzantineValidators)  and a length of 0, and then append it later. Instead of initializing the length to  len(byzantineValidators)  from the beginning, the resulting slice will not meet expectations.
The online demo: https://go.dev/play/p/q1BcVCmvidW
---
I have...
I have...
=> fix: fix slice init length

docs/docusaurus.config.js, docs/package-lock.json, docs/package.json
This PR adds search to ICS docs to help with finding relevant docs.
=> docs: add search to docs

x/ccv/consumer/types/keys.go, x/ccv/provider/keeper/key_assignment.go, x/ccv/provider/types/keys.go
fix some function names in comment
---
I have...
I have...
=> docs: fix some function names in comment

docs/docs/adrs/adr-020-cutomizable_slashing_and_jailing.md, docs/docs/adrs/intro.md
Closes: #XXXX
---
I have...
I have...
=> docs: change the status of ADR 020 as accepted

FEATURES.md, RELEASES.md
Closes: #XXXX
---
I have...
I have...
=> docs: update docs on releases

.github/dependabot.yml, .mergify.yml
Closes: #XXXX
---
I have...
I have...
=> chore: update dependabot and mergify

CHANGELOG.md, RELEASE_NOTES.md
Update release notes and changelog for v6.4.1
=> docs: release notes and changelog for v6.4.1

Dockerfile, Dockerfile.gaia
Updates the golang version in the docker files to resolve docker build failures.
---
=> chore: Update go version in docker files

.mergify.yml
Updates mergify config for the `v7.0.x` branch.
=> chore: Update mergify config
